/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package comws.flau.ci.jdbc;

import comws.flau.ci.dao.*;
import comws.flau.ci.factory.*;
import java.util.Date;
import comws.flau.ci.dto.*;
import comws.flau.ci.exceptions.*;
import java.sql.Connection;
import java.util.Collection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Time;
import java.util.List;
import java.util.Iterator;
import java.util.ArrayList;

public class Tci0004TimesheetcigoDaoImpl extends AbstractDAO implements Tci0004TimesheetcigoDao
{
	/** 
	 * The factory class for this DAO has two versions of the create() method - one that
takes no arguments and one that takes a Connection argument. If the Connection version
is chosen then the connection will be stored in this attribute and will be used by all
calls to this DAO, otherwise a new Connection will be allocated for each operation.
	 */
	protected java.sql.Connection userConn;

	/** 
	 * All finder methods in this class use this SELECT constant to build their queries
	 */
	protected final String SQL_SELECT = "SELECT iddipendente, idcalendario, hh, giorno, idsettimana FROM " + getTableName() + "";

	/** 
	 * Finder methods will pass this value to the JDBC setMaxRows method
	 */
	protected int maxRows;

	/** 
	 * SQL INSERT statement for this table
	 */
	protected final String SQL_INSERT = "INSERT INTO " + getTableName() + " ( iddipendente, idcalendario, hh, giorno, idsettimana ) VALUES ( ?, ?, ?, ?, ? )";

	/** 
	 * SQL UPDATE statement for this table
	 */
	protected final String SQL_UPDATE = "UPDATE " + getTableName() + " SET iddipendente = ?, idcalendario = ?, hh = ?, giorno = ?, idsettimana = ? WHERE iddipendente = ? AND idcalendario = ?";

	/** 
	 * SQL DELETE statement for this table
	 */
	protected final String SQL_DELETE = "DELETE FROM " + getTableName() + " WHERE iddipendente = ? AND idcalendario = ?";

	/** 
	 * Index of column iddipendente
	 */
	protected static final int COLUMN_IDDIPENDENTE = 1;

	/** 
	 * Index of column idcalendario
	 */
	protected static final int COLUMN_IDCALENDARIO = 2;

	/** 
	 * Index of column hh
	 */
	protected static final int COLUMN_HH = 3;

	/** 
	 * Index of column giorno
	 */
	protected static final int COLUMN_GIORNO = 4;

	/** 
	 * Index of column idsettimana
	 */
	protected static final int COLUMN_IDSETTIMANA = 5;

	/** 
	 * Number of columns
	 */
	protected static final int NUMBER_OF_COLUMNS = 5;

	/** 
	 * Index of primary-key column iddipendente
	 */
	protected static final int PK_COLUMN_IDDIPENDENTE = 1;

	/** 
	 * Index of primary-key column idcalendario
	 */
	protected static final int PK_COLUMN_IDCALENDARIO = 2;

	/** 
	 * Inserts a new row in the tci0004_timesheetcigo table.
	 */
	public Tci0004TimesheetcigoPk insert(Tci0004Timesheetcigo dto) throws Tci0004TimesheetcigoDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			stmt = conn.prepareStatement( SQL_INSERT );
			int index = 1;
			stmt.setInt( index++, dto.getIddipendente() );
			stmt.setInt( index++, dto.getIdcalendario() );
			if (dto.isHhNull()) {
				stmt.setNull( index++, java.sql.Types.INTEGER );
			} else {
				stmt.setInt( index++, dto.getHh() );
			}
		
			stmt.setTimestamp(index++, dto.getGiorno()==null ? null : new java.sql.Timestamp( dto.getGiorno().getTime() ) );
			if (dto.isIdsettimanaNull()) {
				stmt.setNull( index++, java.sql.Types.INTEGER );
			} else {
				stmt.setInt( index++, dto.getIdsettimana() );
			}
		
			System.out.println( "Executing " + SQL_INSERT + " with DTO: " + dto );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
			reset(dto);
			return dto.createPk();
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new Tci0004TimesheetcigoDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Updates a single row in the tci0004_timesheetcigo table.
	 */
	public void update(Tci0004TimesheetcigoPk pk, Tci0004Timesheetcigo dto) throws Tci0004TimesheetcigoDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_UPDATE + " with DTO: " + dto );
			stmt = conn.prepareStatement( SQL_UPDATE );
			int index=1;
			stmt.setInt( index++, dto.getIddipendente() );
			stmt.setInt( index++, dto.getIdcalendario() );
			if (dto.isHhNull()) {
				stmt.setNull( index++, java.sql.Types.INTEGER );
			} else {
				stmt.setInt( index++, dto.getHh() );
			}
		
			stmt.setTimestamp(index++, dto.getGiorno()==null ? null : new java.sql.Timestamp( dto.getGiorno().getTime() ) );
			if (dto.isIdsettimanaNull()) {
				stmt.setNull( index++, java.sql.Types.INTEGER );
			} else {
				stmt.setInt( index++, dto.getIdsettimana() );
			}
		
			stmt.setInt( 6, pk.getIddipendente() );
			stmt.setInt( 7, pk.getIdcalendario() );
			int rows = stmt.executeUpdate();
			reset(dto);
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new Tci0004TimesheetcigoDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Deletes a single row in the tci0004_timesheetcigo table.
	 */
	public void delete(Tci0004TimesheetcigoPk pk) throws Tci0004TimesheetcigoDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_DELETE + " with PK: " + pk );
			stmt = conn.prepareStatement( SQL_DELETE );
			stmt.setInt( 1, pk.getIddipendente() );
			stmt.setInt( 2, pk.getIdcalendario() );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new Tci0004TimesheetcigoDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns the rows from the tci0004_timesheetcigo table that matches the specified primary-key value.
	 */
	public Tci0004Timesheetcigo findByPrimaryKey(Tci0004TimesheetcigoPk pk) throws Tci0004TimesheetcigoDaoException
	{
		return findByPrimaryKey( pk.getIddipendente(), pk.getIdcalendario() );
	}

	/** 
	 * Returns all rows from the tci0004_timesheetcigo table that match the criteria 'iddipendente = :iddipendente AND idcalendario = :idcalendario'.
	 */
	public Tci0004Timesheetcigo findByPrimaryKey(int iddipendente, int idcalendario) throws Tci0004TimesheetcigoDaoException
	{
		Tci0004Timesheetcigo ret[] = findByDynamicSelect( SQL_SELECT + " WHERE iddipendente = ? AND idcalendario = ?", new Object[] {  new Integer(iddipendente),  new Integer(idcalendario) } );
		return ret.length==0 ? null : ret[0];
	}

	/** 
	 * Returns all rows from the tci0004_timesheetcigo table that match the criteria ''.
	 */
	public Tci0004Timesheetcigo[] findAll() throws Tci0004TimesheetcigoDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " ORDER BY iddipendente, idcalendario", null );
	}

	/** 
	 * Returns all rows from the tci0004_timesheetcigo table that match the criteria 'iddipendente = :iddipendente'.
	 */
	public Tci0004Timesheetcigo[] findWhereIddipendenteEquals(int iddipendente) throws Tci0004TimesheetcigoDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE iddipendente = ? ORDER BY iddipendente", new Object[] {  new Integer(iddipendente) } );
	}

	/** 
	 * Returns all rows from the tci0004_timesheetcigo table that match the criteria 'idcalendario = :idcalendario'.
	 */
	public Tci0004Timesheetcigo[] findWhereIdcalendarioEquals(int idcalendario) throws Tci0004TimesheetcigoDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE idcalendario = ? ORDER BY idcalendario", new Object[] {  new Integer(idcalendario) } );
	}

	/** 
	 * Returns all rows from the tci0004_timesheetcigo table that match the criteria 'hh = :hh'.
	 */
	public Tci0004Timesheetcigo[] findWhereHhEquals(int hh) throws Tci0004TimesheetcigoDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE hh = ? ORDER BY hh", new Object[] {  new Integer(hh) } );
	}

	/** 
	 * Returns all rows from the tci0004_timesheetcigo table that match the criteria 'giorno = :giorno'.
	 */
	public Tci0004Timesheetcigo[] findWhereGiornoEquals(Date giorno) throws Tci0004TimesheetcigoDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE giorno = ? ORDER BY giorno", new Object[] { giorno==null ? null : new java.sql.Timestamp( giorno.getTime() ) } );
	}

	/** 
	 * Returns all rows from the tci0004_timesheetcigo table that match the criteria 'idsettimana = :idsettimana'.
	 */
	public Tci0004Timesheetcigo[] findWhereIdsettimanaEquals(int idsettimana) throws Tci0004TimesheetcigoDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE idsettimana = ? ORDER BY idsettimana", new Object[] {  new Integer(idsettimana) } );
	}

	/**
	 * Method 'Tci0004TimesheetcigoDaoImpl'
	 * 
	 */
	public Tci0004TimesheetcigoDaoImpl()
	{
	}

	/**
	 * Method 'Tci0004TimesheetcigoDaoImpl'
	 * 
	 * @param userConn
	 */
	public Tci0004TimesheetcigoDaoImpl(final java.sql.Connection userConn)
	{
		this.userConn = userConn;
	}

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows)
	{
		this.maxRows = maxRows;
	}

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows()
	{
		return maxRows;
	}

	/**
	 * Method 'getTableName'
	 * 
	 * @return String
	 */
	public String getTableName()
	{
		return "group700_fig.tci0004_timesheetcigo";
	}

	/** 
	 * Fetches a single row from the result set
	 */
	protected Tci0004Timesheetcigo fetchSingleResult(ResultSet rs) throws SQLException
	{
		if (rs.next()) {
			Tci0004Timesheetcigo dto = new Tci0004Timesheetcigo();
			populateDto( dto, rs);
			return dto;
		} else {
			return null;
		}
		
	}

	/** 
	 * Fetches multiple rows from the result set
	 */
	protected Tci0004Timesheetcigo[] fetchMultiResults(ResultSet rs) throws SQLException
	{
		Collection resultList = new ArrayList();
		while (rs.next()) {
			Tci0004Timesheetcigo dto = new Tci0004Timesheetcigo();
			populateDto( dto, rs);
			resultList.add( dto );
		}
		
		Tci0004Timesheetcigo ret[] = new Tci0004Timesheetcigo[ resultList.size() ];
		resultList.toArray( ret );
		return ret;
	}

	/** 
	 * Populates a DTO with data from a ResultSet
	 */
	protected void populateDto(Tci0004Timesheetcigo dto, ResultSet rs) throws SQLException
	{
		dto.setIddipendente( rs.getInt( COLUMN_IDDIPENDENTE ) );
		dto.setIdcalendario( rs.getInt( COLUMN_IDCALENDARIO ) );
		dto.setHh( rs.getInt( COLUMN_HH ) );
		if (rs.wasNull()) {
			dto.setHhNull( true );
		}
		
		dto.setGiorno( rs.getTimestamp(COLUMN_GIORNO ) );
		dto.setIdsettimana( rs.getInt( COLUMN_IDSETTIMANA ) );
		if (rs.wasNull()) {
			dto.setIdsettimanaNull( true );
		}
		
	}

	/** 
	 * Resets the modified attributes in the DTO
	 */
	protected void reset(Tci0004Timesheetcigo dto)
	{
	}

	/** 
	 * Returns all rows from the tci0004_timesheetcigo table that match the specified arbitrary SQL statement
	 */
	public Tci0004Timesheetcigo[] findByDynamicSelect(String sql, Object[] sqlParams) throws Tci0004TimesheetcigoDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new Tci0004TimesheetcigoDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns all rows from the tci0004_timesheetcigo table that match the specified arbitrary SQL statement
	 */
	public Tci0004Timesheetcigo[] findByDynamicWhere(String sql, Object[] sqlParams) throws Tci0004TimesheetcigoDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = SQL_SELECT + " WHERE " + sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new Tci0004TimesheetcigoDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

}
