/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package comws.flau.ci.jdbc;

import comws.flau.ci.dao.*;
import comws.flau.ci.factory.*;
import java.util.Date;
import comws.flau.ci.dto.*;
import comws.flau.ci.exceptions.*;
import java.sql.Connection;
import java.util.Collection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Time;
import java.util.List;
import java.util.Iterator;
import java.util.ArrayList;

public class Tci0002CalendarioDaoImpl extends AbstractDAO implements Tci0002CalendarioDao
{
	/** 
	 * The factory class for this DAO has two versions of the create() method - one that
takes no arguments and one that takes a Connection argument. If the Connection version
is chosen then the connection will be stored in this attribute and will be used by all
calls to this DAO, otherwise a new Connection will be allocated for each operation.
	 */
	protected java.sql.Connection userConn;

	/** 
	 * All finder methods in this class use this SELECT constant to build their queries
	 */
	protected final String SQL_SELECT = "SELECT id, giorno, anno, mesenum, meselett, giornosett, giornosettlett FROM " + getTableName() + "";

	/** 
	 * Finder methods will pass this value to the JDBC setMaxRows method
	 */
	protected int maxRows;

	/** 
	 * SQL INSERT statement for this table
	 */
	protected final String SQL_INSERT = "INSERT INTO " + getTableName() + " ( id, giorno, anno, mesenum, meselett, giornosett, giornosettlett ) VALUES ( ?, ?, ?, ?, ?, ?, ? )";

	/** 
	 * SQL UPDATE statement for this table
	 */
	protected final String SQL_UPDATE = "UPDATE " + getTableName() + " SET id = ?, giorno = ?, anno = ?, mesenum = ?, meselett = ?, giornosett = ?, giornosettlett = ? WHERE id = ?";

	/** 
	 * SQL DELETE statement for this table
	 */
	protected final String SQL_DELETE = "DELETE FROM " + getTableName() + " WHERE id = ?";

	/** 
	 * Index of column id
	 */
	protected static final int COLUMN_ID = 1;

	/** 
	 * Index of column giorno
	 */
	protected static final int COLUMN_GIORNO = 2;

	/** 
	 * Index of column anno
	 */
	protected static final int COLUMN_ANNO = 3;

	/** 
	 * Index of column mesenum
	 */
	protected static final int COLUMN_MESENUM = 4;

	/** 
	 * Index of column meselett
	 */
	protected static final int COLUMN_MESELETT = 5;

	/** 
	 * Index of column giornosett
	 */
	protected static final int COLUMN_GIORNOSETT = 6;

	/** 
	 * Index of column giornosettlett
	 */
	protected static final int COLUMN_GIORNOSETTLETT = 7;

	/** 
	 * Number of columns
	 */
	protected static final int NUMBER_OF_COLUMNS = 7;

	/** 
	 * Index of primary-key column id
	 */
	protected static final int PK_COLUMN_ID = 1;

	/** 
	 * Inserts a new row in the tci0002_calendario table.
	 */
	public Tci0002CalendarioPk insert(Tci0002Calendario dto) throws Tci0002CalendarioDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			stmt = conn.prepareStatement( SQL_INSERT );
			int index = 1;
			stmt.setInt( index++, dto.getId() );
			stmt.setTimestamp(index++, dto.getGiorno()==null ? null : new java.sql.Timestamp( dto.getGiorno().getTime() ) );
			if (dto.isAnnoNull()) {
				stmt.setNull( index++, java.sql.Types.INTEGER );
			} else {
				stmt.setInt( index++, dto.getAnno() );
			}
		
			if (dto.isMesenumNull()) {
				stmt.setNull( index++, java.sql.Types.INTEGER );
			} else {
				stmt.setInt( index++, dto.getMesenum() );
			}
		
			stmt.setString( index++, dto.getMeselett() );
			if (dto.isGiornosettNull()) {
				stmt.setNull( index++, java.sql.Types.INTEGER );
			} else {
				stmt.setInt( index++, dto.getGiornosett() );
			}
		
			stmt.setString( index++, dto.getGiornosettlett() );
			System.out.println( "Executing " + SQL_INSERT + " with DTO: " + dto );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
			reset(dto);
			return dto.createPk();
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new Tci0002CalendarioDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Updates a single row in the tci0002_calendario table.
	 */
	public void update(Tci0002CalendarioPk pk, Tci0002Calendario dto) throws Tci0002CalendarioDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_UPDATE + " with DTO: " + dto );
			stmt = conn.prepareStatement( SQL_UPDATE );
			int index=1;
			stmt.setInt( index++, dto.getId() );
			stmt.setTimestamp(index++, dto.getGiorno()==null ? null : new java.sql.Timestamp( dto.getGiorno().getTime() ) );
			if (dto.isAnnoNull()) {
				stmt.setNull( index++, java.sql.Types.INTEGER );
			} else {
				stmt.setInt( index++, dto.getAnno() );
			}
		
			if (dto.isMesenumNull()) {
				stmt.setNull( index++, java.sql.Types.INTEGER );
			} else {
				stmt.setInt( index++, dto.getMesenum() );
			}
		
			stmt.setString( index++, dto.getMeselett() );
			if (dto.isGiornosettNull()) {
				stmt.setNull( index++, java.sql.Types.INTEGER );
			} else {
				stmt.setInt( index++, dto.getGiornosett() );
			}
		
			stmt.setString( index++, dto.getGiornosettlett() );
			stmt.setInt( 8, pk.getId() );
			int rows = stmt.executeUpdate();
			reset(dto);
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new Tci0002CalendarioDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Deletes a single row in the tci0002_calendario table.
	 */
	public void delete(Tci0002CalendarioPk pk) throws Tci0002CalendarioDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_DELETE + " with PK: " + pk );
			stmt = conn.prepareStatement( SQL_DELETE );
			stmt.setInt( 1, pk.getId() );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new Tci0002CalendarioDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns the rows from the tci0002_calendario table that matches the specified primary-key value.
	 */
	public Tci0002Calendario findByPrimaryKey(Tci0002CalendarioPk pk) throws Tci0002CalendarioDaoException
	{
		return findByPrimaryKey( pk.getId() );
	}

	/** 
	 * Returns all rows from the tci0002_calendario table that match the criteria 'id = :id'.
	 */
	public Tci0002Calendario findByPrimaryKey(int id) throws Tci0002CalendarioDaoException
	{
		Tci0002Calendario ret[] = findByDynamicSelect( SQL_SELECT + " WHERE id = ?", new Object[] {  new Integer(id) } );
		return ret.length==0 ? null : ret[0];
	}

	/** 
	 * Returns all rows from the tci0002_calendario table that match the criteria ''.
	 */
	public Tci0002Calendario[] findAll() throws Tci0002CalendarioDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " ORDER BY id", null );
	}

	/** 
	 * Returns all rows from the tci0002_calendario table that match the criteria 'id = :id'.
	 */
	public Tci0002Calendario[] findWhereIdEquals(int id) throws Tci0002CalendarioDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE id = ? ORDER BY id", new Object[] {  new Integer(id) } );
	}

	/** 
	 * Returns all rows from the tci0002_calendario table that match the criteria 'giorno = :giorno'.
	 */
	public Tci0002Calendario[] findWhereGiornoEquals(Date giorno) throws Tci0002CalendarioDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE giorno = ? ORDER BY giorno", new Object[] { giorno==null ? null : new java.sql.Timestamp( giorno.getTime() ) } );
	}

	/** 
	 * Returns all rows from the tci0002_calendario table that match the criteria 'anno = :anno'.
	 */
	public Tci0002Calendario[] findWhereAnnoEquals(int anno) throws Tci0002CalendarioDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE anno = ? ORDER BY anno", new Object[] {  new Integer(anno) } );
	}

	/** 
	 * Returns all rows from the tci0002_calendario table that match the criteria 'mesenum = :mesenum'.
	 */
	public Tci0002Calendario[] findWhereMesenumEquals(int mesenum) throws Tci0002CalendarioDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE mesenum = ? ORDER BY mesenum", new Object[] {  new Integer(mesenum) } );
	}

	/** 
	 * Returns all rows from the tci0002_calendario table that match the criteria 'meselett = :meselett'.
	 */
	public Tci0002Calendario[] findWhereMeselettEquals(String meselett) throws Tci0002CalendarioDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE meselett = ? ORDER BY meselett", new Object[] { meselett } );
	}

	/** 
	 * Returns all rows from the tci0002_calendario table that match the criteria 'giornosett = :giornosett'.
	 */
	public Tci0002Calendario[] findWhereGiornosettEquals(int giornosett) throws Tci0002CalendarioDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE giornosett = ? ORDER BY giornosett", new Object[] {  new Integer(giornosett) } );
	}

	/** 
	 * Returns all rows from the tci0002_calendario table that match the criteria 'giornosettlett = :giornosettlett'.
	 */
	public Tci0002Calendario[] findWhereGiornosettlettEquals(String giornosettlett) throws Tci0002CalendarioDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE giornosettlett = ? ORDER BY giornosettlett", new Object[] { giornosettlett } );
	}

	/**
	 * Method 'Tci0002CalendarioDaoImpl'
	 * 
	 */
	public Tci0002CalendarioDaoImpl()
	{
	}

	/**
	 * Method 'Tci0002CalendarioDaoImpl'
	 * 
	 * @param userConn
	 */
	public Tci0002CalendarioDaoImpl(final java.sql.Connection userConn)
	{
		this.userConn = userConn;
	}

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows)
	{
		this.maxRows = maxRows;
	}

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows()
	{
		return maxRows;
	}

	/**
	 * Method 'getTableName'
	 * 
	 * @return String
	 */
	public String getTableName()
	{
		return "group700_fig.tci0002_calendario";
	}

	/** 
	 * Fetches a single row from the result set
	 */
	protected Tci0002Calendario fetchSingleResult(ResultSet rs) throws SQLException
	{
		if (rs.next()) {
			Tci0002Calendario dto = new Tci0002Calendario();
			populateDto( dto, rs);
			return dto;
		} else {
			return null;
		}
		
	}

	/** 
	 * Fetches multiple rows from the result set
	 */
	protected Tci0002Calendario[] fetchMultiResults(ResultSet rs) throws SQLException
	{
		Collection resultList = new ArrayList();
		while (rs.next()) {
			Tci0002Calendario dto = new Tci0002Calendario();
			populateDto( dto, rs);
			resultList.add( dto );
		}
		
		Tci0002Calendario ret[] = new Tci0002Calendario[ resultList.size() ];
		resultList.toArray( ret );
		return ret;
	}

	/** 
	 * Populates a DTO with data from a ResultSet
	 */
	protected void populateDto(Tci0002Calendario dto, ResultSet rs) throws SQLException
	{
		dto.setId( rs.getInt( COLUMN_ID ) );
		dto.setGiorno( rs.getTimestamp(COLUMN_GIORNO ) );
		dto.setAnno( rs.getInt( COLUMN_ANNO ) );
		if (rs.wasNull()) {
			dto.setAnnoNull( true );
		}
		
		dto.setMesenum( rs.getInt( COLUMN_MESENUM ) );
		if (rs.wasNull()) {
			dto.setMesenumNull( true );
		}
		
		dto.setMeselett( rs.getString( COLUMN_MESELETT ) );
		dto.setGiornosett( rs.getInt( COLUMN_GIORNOSETT ) );
		if (rs.wasNull()) {
			dto.setGiornosettNull( true );
		}
		
		dto.setGiornosettlett( rs.getString( COLUMN_GIORNOSETTLETT ) );
	}

	/** 
	 * Resets the modified attributes in the DTO
	 */
	protected void reset(Tci0002Calendario dto)
	{
	}

	/** 
	 * Returns all rows from the tci0002_calendario table that match the specified arbitrary SQL statement
	 */
	public Tci0002Calendario[] findByDynamicSelect(String sql, Object[] sqlParams) throws Tci0002CalendarioDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new Tci0002CalendarioDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns all rows from the tci0002_calendario table that match the specified arbitrary SQL statement
	 */
	public Tci0002Calendario[] findByDynamicWhere(String sql, Object[] sqlParams) throws Tci0002CalendarioDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = SQL_SELECT + " WHERE " + sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new Tci0002CalendarioDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

}
