/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package comws.flau.ci.exceptions;

public class Tsa1005ContutenzeDaoException extends DaoException
{
	/**
	 * Method 'Tsa1005ContutenzeDaoException'
	 * 
	 * @param message
	 */
	public Tsa1005ContutenzeDaoException(String message)
	{
		super(message);
	}

	/**
	 * Method 'Tsa1005ContutenzeDaoException'
	 * 
	 * @param message
	 * @param cause
	 */
	public Tsa1005ContutenzeDaoException(String message, Throwable cause)
	{
		super(message, cause);
	}

}
