/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package comws.flau.ci.exceptions;

public class Vsa1003UteprofiliDaoException extends DaoException
{
	/**
	 * Method 'Vsa1003UteprofiliDaoException'
	 * 
	 * @param message
	 */
	public Vsa1003UteprofiliDaoException(String message)
	{
		super(message);
	}

	/**
	 * Method 'Vsa1003UteprofiliDaoException'
	 * 
	 * @param message
	 * @param cause
	 */
	public Vsa1003UteprofiliDaoException(String message, Throwable cause)
	{
		super(message, cause);
	}

}
