/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package comws.flau.ci.dao;

import java.util.Date;
import comws.flau.ci.dto.*;
import comws.flau.ci.exceptions.*;

public interface Tci0004TimesheetcigoDao
{
	/** 
	 * Inserts a new row in the tci0004_timesheetcigo table.
	 */
	public Tci0004TimesheetcigoPk insert(Tci0004Timesheetcigo dto) throws Tci0004TimesheetcigoDaoException;

	/** 
	 * Updates a single row in the tci0004_timesheetcigo table.
	 */
	public void update(Tci0004TimesheetcigoPk pk, Tci0004Timesheetcigo dto) throws Tci0004TimesheetcigoDaoException;

	/** 
	 * Deletes a single row in the tci0004_timesheetcigo table.
	 */
	public void delete(Tci0004TimesheetcigoPk pk) throws Tci0004TimesheetcigoDaoException;

	/** 
	 * Returns the rows from the tci0004_timesheetcigo table that matches the specified primary-key value.
	 */
	public Tci0004Timesheetcigo findByPrimaryKey(Tci0004TimesheetcigoPk pk) throws Tci0004TimesheetcigoDaoException;

	/** 
	 * Returns all rows from the tci0004_timesheetcigo table that match the criteria 'iddipendente = :iddipendente AND idcalendario = :idcalendario'.
	 */
	public Tci0004Timesheetcigo findByPrimaryKey(int iddipendente, int idcalendario) throws Tci0004TimesheetcigoDaoException;

	/** 
	 * Returns all rows from the tci0004_timesheetcigo table that match the criteria ''.
	 */
	public Tci0004Timesheetcigo[] findAll() throws Tci0004TimesheetcigoDaoException;

	/** 
	 * Returns all rows from the tci0004_timesheetcigo table that match the criteria 'iddipendente = :iddipendente'.
	 */
	public Tci0004Timesheetcigo[] findWhereIddipendenteEquals(int iddipendente) throws Tci0004TimesheetcigoDaoException;

	/** 
	 * Returns all rows from the tci0004_timesheetcigo table that match the criteria 'idcalendario = :idcalendario'.
	 */
	public Tci0004Timesheetcigo[] findWhereIdcalendarioEquals(int idcalendario) throws Tci0004TimesheetcigoDaoException;

	/** 
	 * Returns all rows from the tci0004_timesheetcigo table that match the criteria 'hh = :hh'.
	 */
	public Tci0004Timesheetcigo[] findWhereHhEquals(int hh) throws Tci0004TimesheetcigoDaoException;

	/** 
	 * Returns all rows from the tci0004_timesheetcigo table that match the criteria 'giorno = :giorno'.
	 */
	public Tci0004Timesheetcigo[] findWhereGiornoEquals(Date giorno) throws Tci0004TimesheetcigoDaoException;

	/** 
	 * Returns all rows from the tci0004_timesheetcigo table that match the criteria 'idsettimana = :idsettimana'.
	 */
	public Tci0004Timesheetcigo[] findWhereIdsettimanaEquals(int idsettimana) throws Tci0004TimesheetcigoDaoException;

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows);

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows();

	/** 
	 * Returns all rows from the tci0004_timesheetcigo table that match the specified arbitrary SQL statement
	 */
	public Tci0004Timesheetcigo[] findByDynamicSelect(String sql, Object[] sqlParams) throws Tci0004TimesheetcigoDaoException;

	/** 
	 * Returns all rows from the tci0004_timesheetcigo table that match the specified arbitrary SQL statement
	 */
	public Tci0004Timesheetcigo[] findByDynamicWhere(String sql, Object[] sqlParams) throws Tci0004TimesheetcigoDaoException;

}
