/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package comws.flau.ci.dao;

import java.util.Date;
import comws.flau.ci.dto.*;
import comws.flau.ci.exceptions.*;

public interface Tci0003DipendentecigoDao
{
	/** 
	 * Inserts a new row in the tci0003_dipendentecigo table.
	 */
	public Tci0003DipendentecigoPk insert(Tci0003Dipendentecigo dto) throws Tci0003DipendentecigoDaoException;

	/** 
	 * Updates a single row in the tci0003_dipendentecigo table.
	 */
	public void update(Tci0003DipendentecigoPk pk, Tci0003Dipendentecigo dto) throws Tci0003DipendentecigoDaoException;

	/** 
	 * Deletes a single row in the tci0003_dipendentecigo table.
	 */
	public void delete(Tci0003DipendentecigoPk pk) throws Tci0003DipendentecigoDaoException;

	/** 
	 * Returns the rows from the tci0003_dipendentecigo table that matches the specified primary-key value.
	 */
	public Tci0003Dipendentecigo findByPrimaryKey(Tci0003DipendentecigoPk pk) throws Tci0003DipendentecigoDaoException;

	/** 
	 * Returns all rows from the tci0003_dipendentecigo table that match the criteria 'pr = :pr'.
	 */
	public Tci0003Dipendentecigo findByPrimaryKey(int pr) throws Tci0003DipendentecigoDaoException;

	/** 
	 * Returns all rows from the tci0003_dipendentecigo table that match the criteria 'full-time = :fullTime'.
	 */
	public Tci0003Dipendentecigo[] findWhereFullTimeEquals(String fullTime) throws Tci0003DipendentecigoDaoException;

	/** 
	 * Returns all rows from the tci0003_dipendentecigo table that match the criteria ''.
	 */
	public Tci0003Dipendentecigo[] findAll() throws Tci0003DipendentecigoDaoException;

	/** 
	 * Returns all rows from the tci0003_dipendentecigo table that match the criteria 'pr = :pr'.
	 */
	public Tci0003Dipendentecigo[] findWherePrEquals(int pr) throws Tci0003DipendentecigoDaoException;

	/** 
	 * Returns all rows from the tci0003_dipendentecigo table that match the criteria 'iddipendente = :iddipendente'.
	 */
	public Tci0003Dipendentecigo[] findWhereIddipendenteEquals(int iddipendente) throws Tci0003DipendentecigoDaoException;

	/** 
	 * Returns all rows from the tci0003_dipendentecigo table that match the criteria 'Commessa = :commessa'.
	 */
	public Tci0003Dipendentecigo[] findWhereCommessaEquals(String commessa) throws Tci0003DipendentecigoDaoException;

	/** 
	 * Returns all rows from the tci0003_dipendentecigo table that match the criteria 'allocato = :allocato'.
	 */
	public Tci0003Dipendentecigo[] findWhereAllocatoEquals(String allocato) throws Tci0003DipendentecigoDaoException;

	/** 
	 * Returns all rows from the tci0003_dipendentecigo table that match the criteria 'fulltime = :fulltime'.
	 */
	public Tci0003Dipendentecigo[] findWhereFulltimeEquals(String fulltime) throws Tci0003DipendentecigoDaoException;

	/** 
	 * Returns all rows from the tci0003_dipendentecigo table that match the criteria 'reparto = :reparto'.
	 */
	public Tci0003Dipendentecigo[] findWhereRepartoEquals(String reparto) throws Tci0003DipendentecigoDaoException;

	/** 
	 * Returns all rows from the tci0003_dipendentecigo table that match the criteria 'PercentualeCIGO = :percentualeCIGO'.
	 */
	public Tci0003Dipendentecigo[] findWherePercentualeCIGOEquals(int percentualeCIGO) throws Tci0003DipendentecigoDaoException;

	/** 
	 * Returns all rows from the tci0003_dipendentecigo table that match the criteria 'datainizio = :datainizio'.
	 */
	public Tci0003Dipendentecigo[] findWhereDatainizioEquals(Date datainizio) throws Tci0003DipendentecigoDaoException;

	/** 
	 * Returns all rows from the tci0003_dipendentecigo table that match the criteria 'datafine = :datafine'.
	 */
	public Tci0003Dipendentecigo[] findWhereDatafineEquals(Date datafine) throws Tci0003DipendentecigoDaoException;

	/** 
	 * Returns all rows from the tci0003_dipendentecigo table that match the criteria 'datarientroanticipato = :datarientroanticipato'.
	 */
	public Tci0003Dipendentecigo[] findWhereDatarientroanticipatoEquals(Date datarientroanticipato) throws Tci0003DipendentecigoDaoException;

	/** 
	 * Returns all rows from the tci0003_dipendentecigo table that match the criteria 'formazione = :formazione'.
	 */
	public Tci0003Dipendentecigo[] findWhereFormazioneEquals(String formazione) throws Tci0003DipendentecigoDaoException;

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows);

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows();

	/** 
	 * Returns all rows from the tci0003_dipendentecigo table that match the specified arbitrary SQL statement
	 */
	public Tci0003Dipendentecigo[] findByDynamicSelect(String sql, Object[] sqlParams) throws Tci0003DipendentecigoDaoException;

	/** 
	 * Returns all rows from the tci0003_dipendentecigo table that match the specified arbitrary SQL statement
	 */
	public Tci0003Dipendentecigo[] findByDynamicWhere(String sql, Object[] sqlParams) throws Tci0003DipendentecigoDaoException;

}
