/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package comws.flau.ci.dao;

import java.util.Date;
import comws.flau.ci.dto.*;
import comws.flau.ci.exceptions.*;

public interface Tsa1005ContutenzeDao
{
	/** 
	 * Inserts a new row in the tsa1005_contutenze table.
	 */
	public Tsa1005ContutenzePk insert(Tsa1005Contutenze dto) throws Tsa1005ContutenzeDaoException;

	/** 
	 * Updates a single row in the tsa1005_contutenze table.
	 */
	public void update(Tsa1005ContutenzePk pk, Tsa1005Contutenze dto) throws Tsa1005ContutenzeDaoException;

	/** 
	 * Deletes a single row in the tsa1005_contutenze table.
	 */
	public void delete(Tsa1005ContutenzePk pk) throws Tsa1005ContutenzeDaoException;

	/** 
	 * Returns the rows from the tsa1005_contutenze table that matches the specified primary-key value.
	 */
	public Tsa1005Contutenze findByPrimaryKey(Tsa1005ContutenzePk pk) throws Tsa1005ContutenzeDaoException;

	/** 
	 * Returns all rows from the tsa1005_contutenze table that match the criteria 'PRG_CNT = :prgCnt AND PRG_UTE = :prgUte AND PRG_PRF_FGL = :prgPrfFgl AND PRG_PRF_PDR = :prgPrfPdr AND PRG_APP = :prgApp AND ORD_CNT = :ordCnt'.
	 */
	public Tsa1005Contutenze findByPrimaryKey(int prgCnt, int prgUte, int prgPrfFgl, int prgPrfPdr, int prgApp, int ordCnt) throws Tsa1005ContutenzeDaoException;

	/** 
	 * Returns all rows from the tsa1005_contutenze table that match the criteria ''.
	 */
	public Tsa1005Contutenze[] findAll() throws Tsa1005ContutenzeDaoException;

	/** 
	 * Returns all rows from the tsa1005_contutenze table that match the criteria 'DES_VAL_CNT = :desValCnt'.
	 */
	public Tsa1005Contutenze[] findWhereDesValCntEquals(String desValCnt) throws Tsa1005ContutenzeDaoException;

	/** 
	 * Returns all rows from the tsa1005_contutenze table that match the criteria 'ORD_CNT = :ordCnt'.
	 */
	public Tsa1005Contutenze[] findWhereOrdCntEquals(int ordCnt) throws Tsa1005ContutenzeDaoException;

	/** 
	 * Returns all rows from the tsa1005_contutenze table that match the criteria 'PRG_CNT = :prgCnt'.
	 */
	public Tsa1005Contutenze[] findWherePrgCntEquals(int prgCnt) throws Tsa1005ContutenzeDaoException;

	/** 
	 * Returns all rows from the tsa1005_contutenze table that match the criteria 'PRG_PRF_FGL = :prgPrfFgl'.
	 */
	public Tsa1005Contutenze[] findWherePrgPrfFglEquals(int prgPrfFgl) throws Tsa1005ContutenzeDaoException;

	/** 
	 * Returns all rows from the tsa1005_contutenze table that match the criteria 'PRG_UTE = :prgUte AND PRG_APP = :prgApp AND PRG_PRF_PDR = :prgPrfPdr AND PRG_PRF_FGL = :prgPrfFgl'.
	 */
	public Tsa1005Contutenze[] findWherePrgAppUtePdrFglEquals(int prgUte, int prgApp, int prgPrfPdr, int prgPrfFgl) throws Tsa1005ContutenzeDaoException;

	/** 
	 * Returns all rows from the tsa1005_contutenze table that match the criteria 'PRG_PRF_PDR = :prgPrfPdr'.
	 */
	public Tsa1005Contutenze[] findWherePrgPrfPdrEquals(int prgPrfPdr) throws Tsa1005ContutenzeDaoException;

	/** 
	 * Returns all rows from the tsa1005_contutenze table that match the criteria 'FLG_ABL = :flgAbl'.
	 */
	public Tsa1005Contutenze[] findWhereFlgAblEquals(String flgAbl) throws Tsa1005ContutenzeDaoException;

	/** 
	 * Returns all rows from the tsa1005_contutenze table that match the criteria 'PRG_APP = :prgApp'.
	 */
	public Tsa1005Contutenze[] findWherePrgAppEquals(int prgApp) throws Tsa1005ContutenzeDaoException;

	/** 
	 * Returns all rows from the tsa1005_contutenze table that match the criteria 'FLG_CAN = :flgCan'.
	 */
	public Tsa1005Contutenze[] findWhereFlgCanEquals(String flgCan) throws Tsa1005ContutenzeDaoException;

	/** 
	 * Returns all rows from the tsa1005_contutenze table that match the criteria 'FLG_TRA_DAT = :flgTraDat'.
	 */
	public Tsa1005Contutenze[] findWhereFlgTraDatEquals(String flgTraDat) throws Tsa1005ContutenzeDaoException;

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows);

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows();

	/** 
	 * Returns all rows from the tsa1005_contutenze table that match the specified arbitrary SQL statement
	 */
	public Tsa1005Contutenze[] findByDynamicSelect(String sql, Object[] sqlParams) throws Tsa1005ContutenzeDaoException;

	/** 
	 * Returns all rows from the tsa1005_contutenze table that match the specified arbitrary SQL statement
	 */
	public Tsa1005Contutenze[] findByDynamicWhere(String sql, Object[] sqlParams) throws Tsa1005ContutenzeDaoException;

}
