/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package comws.flau.ci.dao;

import java.util.Date;
import comws.flau.ci.dto.*;
import comws.flau.ci.exceptions.*;

public interface VciElenco002Dao
{
	/** 
	 * Returns all rows from the vci_elenco002 table that match the criteria ''.
	 */
	public VciElenco002[] findAll() throws VciElenco002DaoException;

	/** 
	 * Returns all rows from the vci_elenco002 table that match the criteria 'PRG_UTE = :prgUte'.
	 */
	public VciElenco002[] findWherePrgUteEquals(int prgUte) throws VciElenco002DaoException;

	/** 
	 * Returns all rows from the vci_elenco002 table that match the criteria 'id = :id'.
	 */
	public VciElenco002[] findWhereIdEquals(int id) throws VciElenco002DaoException;

	/** 
	 * Returns all rows from the vci_elenco002 table that match the criteria 'giorno = :giorno'.
	 */
	public VciElenco002[] findWhereGiornoEquals(Date giorno) throws VciElenco002DaoException;

	/** 
	 * Returns all rows from the vci_elenco002 table that match the criteria 'anno = :anno'.
	 */
	public VciElenco002[] findWhereAnnoEquals(int anno) throws VciElenco002DaoException;

	/** 
	 * Returns all rows from the vci_elenco002 table that match the criteria 'mesenum = :mesenum'.
	 */
	public VciElenco002[] findWhereMesenumEquals(int mesenum) throws VciElenco002DaoException;

	/** 
	 * Returns all rows from the vci_elenco002 table that match the criteria 'meselett = :meselett'.
	 */
	public VciElenco002[] findWhereMeselettEquals(String meselett) throws VciElenco002DaoException;

	/** 
	 * Returns all rows from the vci_elenco002 table that match the criteria 'giornosett = :giornosett'.
	 */
	public VciElenco002[] findWhereGiornosettEquals(int giornosett) throws VciElenco002DaoException;

	/** 
	 * Returns all rows from the vci_elenco002 table that match the criteria 'giornosettlett = :giornosettlett'.
	 */
	public VciElenco002[] findWhereGiornosettlettEquals(String giornosettlett) throws VciElenco002DaoException;

	/** 
	 * Returns all rows from the vci_elenco002 table that match the criteria 'hh = :hh'.
	 */
	public VciElenco002[] findWhereHhEquals(int hh) throws VciElenco002DaoException;

	/** 
	 * Returns all rows from the vci_elenco002 table that match the criteria 'idsettimana = :idsettimana'.
	 */
	public VciElenco002[] findWhereIdsettimanaEquals(int idsettimana) throws VciElenco002DaoException;

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows);

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows();

	/** 
	 * Returns all rows from the vci_elenco002 table that match the specified arbitrary SQL statement
	 */
	public VciElenco002[] findByDynamicSelect(String sql, Object[] sqlParams) throws VciElenco002DaoException;

	/** 
	 * Returns all rows from the vci_elenco002 table that match the specified arbitrary SQL statement
	 */
	public VciElenco002[] findByDynamicWhere(String sql, Object[] sqlParams) throws VciElenco002DaoException;

}
