/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package comws.flau.ci.factory;

import java.sql.Connection;
import comws.flau.ci.dao.*;
import comws.flau.ci.jdbc.*;

public class Tci0003DipendentecigoDaoFactory
{
	/**
	 * Method 'create'
	 * 
	 * @return Tci0003DipendentecigoDao
	 */
	public static Tci0003DipendentecigoDao create()
	{
		return new Tci0003DipendentecigoDaoImpl();
	}

	/**
	 * Method 'create'
	 * 
	 * @param conn
	 * @return Tci0003DipendentecigoDao
	 */
	public static Tci0003DipendentecigoDao create(Connection conn)
	{
		return new Tci0003DipendentecigoDaoImpl( conn );
	}

}
