/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package comws.flau.ci.factory;

import java.sql.Connection;
import comws.flau.ci.dao.*;
import comws.flau.ci.jdbc.*;

public class Tsa1010UtenzaDaoFactory
{
	/**
	 * Method 'create'
	 * 
	 * @return Tsa1010UtenzaDao
	 */
	public static Tsa1010UtenzaDao create()
	{
		return new Tsa1010UtenzaDaoImpl();
	}

	/**
	 * Method 'create'
	 * 
	 * @param conn
	 * @return Tsa1010UtenzaDao
	 */
	public static Tsa1010UtenzaDao create(Connection conn)
	{
		return new Tsa1010UtenzaDaoImpl( conn );
	}

}
