/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package comws.flau.ci.factory;

import java.sql.Connection;
import comws.flau.ci.dao.*;
import comws.flau.ci.jdbc.*;

public class VciElenco001DaoFactory
{
	/**
	 * Method 'create'
	 * 
	 * @return VciElenco001Dao
	 */
	public static VciElenco001Dao create()
	{
		return new VciElenco001DaoImpl();
	}

	/**
	 * Method 'create'
	 * 
	 * @param conn
	 * @return VciElenco001Dao
	 */
	public static VciElenco001Dao create(Connection conn)
	{
		return new VciElenco001DaoImpl( conn );
	}

}
