/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package comws.flau.ci.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the tci0003_dipendentecigo table.
 */
public class Tci0003DipendentecigoPk implements Serializable
{
	protected int pr;

	/** 
	 * This attribute represents whether the primitive attribute pr is null.
	 */
	protected boolean prNull;

	/** 
	 * Sets the value of pr
	 */
	public void setPr(int pr)
	{
		this.pr = pr;
	}

	/** 
	 * Gets the value of pr
	 */
	public int getPr()
	{
		return pr;
	}

	/**
	 * Method 'Tci0003DipendentecigoPk'
	 * 
	 */
	public Tci0003DipendentecigoPk()
	{
	}

	/**
	 * Method 'Tci0003DipendentecigoPk'
	 * 
	 * @param pr
	 */
	public Tci0003DipendentecigoPk(final int pr)
	{
		this.pr = pr;
	}

	/** 
	 * Sets the value of prNull
	 */
	public void setPrNull(boolean prNull)
	{
		this.prNull = prNull;
	}

	/** 
	 * Gets the value of prNull
	 */
	public boolean isPrNull()
	{
		return prNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Tci0003DipendentecigoPk)) {
			return false;
		}
		
		final Tci0003DipendentecigoPk _cast = (Tci0003DipendentecigoPk) _other;
		if (pr != _cast.pr) {
			return false;
		}
		
		if (prNull != _cast.prNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + pr;
		_hashCode = 29 * _hashCode + (prNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "comws.flau.ci.dto.Tci0003DipendentecigoPk: " );
		ret.append( "pr=" + pr );
		return ret.toString();
	}

}
