/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package comws.flau.ci.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the tci0001_elenco table.
 */
public class Tci0001ElencoPk implements Serializable
{
	protected int prgUte;

	/** 
	 * This attribute represents whether the primitive attribute prgUte is null.
	 */
	protected boolean prgUteNull;

	/** 
	 * Sets the value of prgUte
	 */
	public void setPrgUte(int prgUte)
	{
		this.prgUte = prgUte;
	}

	/** 
	 * Gets the value of prgUte
	 */
	public int getPrgUte()
	{
		return prgUte;
	}

	/**
	 * Method 'Tci0001ElencoPk'
	 * 
	 */
	public Tci0001ElencoPk()
	{
	}

	/**
	 * Method 'Tci0001ElencoPk'
	 * 
	 * @param prgUte
	 */
	public Tci0001ElencoPk(final int prgUte)
	{
		this.prgUte = prgUte;
	}

	/** 
	 * Sets the value of prgUteNull
	 */
	public void setPrgUteNull(boolean prgUteNull)
	{
		this.prgUteNull = prgUteNull;
	}

	/** 
	 * Gets the value of prgUteNull
	 */
	public boolean isPrgUteNull()
	{
		return prgUteNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Tci0001ElencoPk)) {
			return false;
		}
		
		final Tci0001ElencoPk _cast = (Tci0001ElencoPk) _other;
		if (prgUte != _cast.prgUte) {
			return false;
		}
		
		if (prgUteNull != _cast.prgUteNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + prgUte;
		_hashCode = 29 * _hashCode + (prgUteNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "comws.flau.ci.dto.Tci0001ElencoPk: " );
		ret.append( "prgUte=" + prgUte );
		return ret.toString();
	}

}
