/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package comws.flau.ci.dto;

import comws.flau.ci.dao.*;
import comws.flau.ci.factory.*;
import comws.flau.ci.exceptions.*;
import java.io.Serializable;
import java.util.*;
import java.util.Date;

public class Tci0004Timesheetcigo implements Serializable
{
	/** 
	 * This attribute maps to the column iddipendente in the tci0004_timesheetcigo table.
	 */
	protected int iddipendente;

	/** 
	 * This attribute maps to the column idcalendario in the tci0004_timesheetcigo table.
	 */
	protected int idcalendario;

	/** 
	 * This attribute maps to the column hh in the tci0004_timesheetcigo table.
	 */
	protected int hh;

	/** 
	 * This attribute represents whether the primitive attribute hh is null.
	 */
	protected boolean hhNull = true;

	/** 
	 * This attribute maps to the column giorno in the tci0004_timesheetcigo table.
	 */
	protected Date giorno;

	/** 
	 * This attribute maps to the column idsettimana in the tci0004_timesheetcigo table.
	 */
	protected int idsettimana;

	/** 
	 * This attribute represents whether the primitive attribute idsettimana is null.
	 */
	protected boolean idsettimanaNull = true;

	/**
	 * Method 'Tci0004Timesheetcigo'
	 * 
	 */
	public Tci0004Timesheetcigo()
	{
	}

	/**
	 * Method 'getIddipendente'
	 * 
	 * @return int
	 */
	public int getIddipendente()
	{
		return iddipendente;
	}

	/**
	 * Method 'setIddipendente'
	 * 
	 * @param iddipendente
	 */
	public void setIddipendente(int iddipendente)
	{
		this.iddipendente = iddipendente;
	}

	/**
	 * Method 'getIdcalendario'
	 * 
	 * @return int
	 */
	public int getIdcalendario()
	{
		return idcalendario;
	}

	/**
	 * Method 'setIdcalendario'
	 * 
	 * @param idcalendario
	 */
	public void setIdcalendario(int idcalendario)
	{
		this.idcalendario = idcalendario;
	}

	/**
	 * Method 'getHh'
	 * 
	 * @return int
	 */
	public int getHh()
	{
		return hh;
	}

	/**
	 * Method 'setHh'
	 * 
	 * @param hh
	 */
	public void setHh(int hh)
	{
		this.hh = hh;
		this.hhNull = false;
	}

	/**
	 * Method 'setHhNull'
	 * 
	 * @param value
	 */
	public void setHhNull(boolean value)
	{
		this.hhNull = value;
	}

	/**
	 * Method 'isHhNull'
	 * 
	 * @return boolean
	 */
	public boolean isHhNull()
	{
		return hhNull;
	}

	/**
	 * Method 'getGiorno'
	 * 
	 * @return Date
	 */
	public Date getGiorno()
	{
		return giorno;
	}

	/**
	 * Method 'setGiorno'
	 * 
	 * @param giorno
	 */
	public void setGiorno(Date giorno)
	{
		this.giorno = giorno;
	}

	/**
	 * Method 'getIdsettimana'
	 * 
	 * @return int
	 */
	public int getIdsettimana()
	{
		return idsettimana;
	}

	/**
	 * Method 'setIdsettimana'
	 * 
	 * @param idsettimana
	 */
	public void setIdsettimana(int idsettimana)
	{
		this.idsettimana = idsettimana;
		this.idsettimanaNull = false;
	}

	/**
	 * Method 'setIdsettimanaNull'
	 * 
	 * @param value
	 */
	public void setIdsettimanaNull(boolean value)
	{
		this.idsettimanaNull = value;
	}

	/**
	 * Method 'isIdsettimanaNull'
	 * 
	 * @return boolean
	 */
	public boolean isIdsettimanaNull()
	{
		return idsettimanaNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Tci0004Timesheetcigo)) {
			return false;
		}
		
		final Tci0004Timesheetcigo _cast = (Tci0004Timesheetcigo) _other;
		if (iddipendente != _cast.iddipendente) {
			return false;
		}
		
		if (idcalendario != _cast.idcalendario) {
			return false;
		}
		
		if (hh != _cast.hh) {
			return false;
		}
		
		if (hhNull != _cast.hhNull) {
			return false;
		}
		
		if (giorno == null ? _cast.giorno != giorno : !giorno.equals( _cast.giorno )) {
			return false;
		}
		
		if (idsettimana != _cast.idsettimana) {
			return false;
		}
		
		if (idsettimanaNull != _cast.idsettimanaNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + iddipendente;
		_hashCode = 29 * _hashCode + idcalendario;
		_hashCode = 29 * _hashCode + hh;
		_hashCode = 29 * _hashCode + (hhNull ? 1 : 0);
		if (giorno != null) {
			_hashCode = 29 * _hashCode + giorno.hashCode();
		}
		
		_hashCode = 29 * _hashCode + idsettimana;
		_hashCode = 29 * _hashCode + (idsettimanaNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return Tci0004TimesheetcigoPk
	 */
	public Tci0004TimesheetcigoPk createPk()
	{
		return new Tci0004TimesheetcigoPk(iddipendente, idcalendario);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "comws.flau.ci.dto.Tci0004Timesheetcigo: " );
		ret.append( "iddipendente=" + iddipendente );
		ret.append( ", idcalendario=" + idcalendario );
		ret.append( ", hh=" + hh );
		ret.append( ", giorno=" + giorno );
		ret.append( ", idsettimana=" + idsettimana );
		return ret.toString();
	}

}
