/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package comws.flau.ci.dto;

import comws.flau.ci.dao.*;
import comws.flau.ci.factory.*;
import comws.flau.ci.exceptions.*;
import java.io.Serializable;
import java.util.*;
import java.util.Date;

public class Tci0003Dipendentecigo implements Serializable
{
	/** 
	 * This attribute maps to the column pr in the tci0003_dipendentecigo table.
	 */
	protected int pr;

	/** 
	 * This attribute maps to the column iddipendente in the tci0003_dipendentecigo table.
	 */
	protected int iddipendente;

	/** 
	 * This attribute represents whether the primitive attribute iddipendente is null.
	 */
	protected boolean iddipendenteNull = true;

	/** 
	 * This attribute maps to the column Commessa in the tci0003_dipendentecigo table.
	 */
	protected String commessa;

	/** 
	 * This attribute maps to the column allocato in the tci0003_dipendentecigo table.
	 */
	protected String allocato;

	/** 
	 * This attribute maps to the column reparto in the tci0003_dipendentecigo table.
	 */
	protected String reparto;

	/** 
	 * This attribute maps to the column PercentualeCIGO in the tci0003_dipendentecigo table.
	 */
	protected int percentualeCIGO;

	/** 
	 * This attribute represents whether the primitive attribute percentualeCIGO is null.
	 */
	protected boolean percentualeCIGONull = true;

	/** 
	 * This attribute maps to the column datainizio in the tci0003_dipendentecigo table.
	 */
	protected Date datainizio;

	/** 
	 * This attribute maps to the column datafine in the tci0003_dipendentecigo table.
	 */
	protected Date datafine;

	/** 
	 * This attribute maps to the column datarientroanticipato in the tci0003_dipendentecigo table.
	 */
	protected Date datarientroanticipato;

	/** 
	 * This attribute maps to the column formazione in the tci0003_dipendentecigo table.
	 */
	protected String formazione;

	/** 
	 * This attribute maps to the column fulltime in the tci0003_dipendentecigo table.
	 */
	protected String fulltime;

	/**
	 * Method 'Tci0003Dipendentecigo'
	 * 
	 */
	public Tci0003Dipendentecigo()
	{
	}

	/**
	 * Method 'getPr'
	 * 
	 * @return int
	 */
	public int getPr()
	{
		return pr;
	}

	/**
	 * Method 'setPr'
	 * 
	 * @param pr
	 */
	public void setPr(int pr)
	{
		this.pr = pr;
	}

	/**
	 * Method 'getIddipendente'
	 * 
	 * @return int
	 */
	public int getIddipendente()
	{
		return iddipendente;
	}

	/**
	 * Method 'setIddipendente'
	 * 
	 * @param iddipendente
	 */
	public void setIddipendente(int iddipendente)
	{
		this.iddipendente = iddipendente;
		this.iddipendenteNull = false;
	}

	/**
	 * Method 'setIddipendenteNull'
	 * 
	 * @param value
	 */
	public void setIddipendenteNull(boolean value)
	{
		this.iddipendenteNull = value;
	}

	/**
	 * Method 'isIddipendenteNull'
	 * 
	 * @return boolean
	 */
	public boolean isIddipendenteNull()
	{
		return iddipendenteNull;
	}

	/**
	 * Method 'getCommessa'
	 * 
	 * @return String
	 */
	public String getCommessa()
	{
		return commessa;
	}

	/**
	 * Method 'setCommessa'
	 * 
	 * @param commessa
	 */
	public void setCommessa(String commessa)
	{
		this.commessa = commessa;
	}

	/**
	 * Method 'getAllocato'
	 * 
	 * @return String
	 */
	public String getAllocato()
	{
		return allocato;
	}

	/**
	 * Method 'setAllocato'
	 * 
	 * @param allocato
	 */
	public void setAllocato(String allocato)
	{
		this.allocato = allocato;
	}

	/**
	 * Method 'getReparto'
	 * 
	 * @return String
	 */
	public String getReparto()
	{
		return reparto;
	}

	/**
	 * Method 'setReparto'
	 * 
	 * @param reparto
	 */
	public void setReparto(String reparto)
	{
		this.reparto = reparto;
	}

	/**
	 * Method 'getPercentualeCIGO'
	 * 
	 * @return int
	 */
	public int getPercentualeCIGO()
	{
		return percentualeCIGO;
	}

	/**
	 * Method 'setPercentualeCIGO'
	 * 
	 * @param percentualeCIGO
	 */
	public void setPercentualeCIGO(int percentualeCIGO)
	{
		this.percentualeCIGO = percentualeCIGO;
		this.percentualeCIGONull = false;
	}

	/**
	 * Method 'setPercentualeCIGONull'
	 * 
	 * @param value
	 */
	public void setPercentualeCIGONull(boolean value)
	{
		this.percentualeCIGONull = value;
	}

	/**
	 * Method 'isPercentualeCIGONull'
	 * 
	 * @return boolean
	 */
	public boolean isPercentualeCIGONull()
	{
		return percentualeCIGONull;
	}

	/**
	 * Method 'getDatainizio'
	 * 
	 * @return Date
	 */
	public Date getDatainizio()
	{
		return datainizio;
	}

	/**
	 * Method 'setDatainizio'
	 * 
	 * @param datainizio
	 */
	public void setDatainizio(Date datainizio)
	{
		this.datainizio = datainizio;
	}

	/**
	 * Method 'getDatafine'
	 * 
	 * @return Date
	 */
	public Date getDatafine()
	{
		return datafine;
	}

	/**
	 * Method 'setDatafine'
	 * 
	 * @param datafine
	 */
	public void setDatafine(Date datafine)
	{
		this.datafine = datafine;
	}

	/**
	 * Method 'getDatarientroanticipato'
	 * 
	 * @return Date
	 */
	public Date getDatarientroanticipato()
	{
		return datarientroanticipato;
	}

	/**
	 * Method 'setDatarientroanticipato'
	 * 
	 * @param datarientroanticipato
	 */
	public void setDatarientroanticipato(Date datarientroanticipato)
	{
		this.datarientroanticipato = datarientroanticipato;
	}

	/**
	 * Method 'getFormazione'
	 * 
	 * @return String
	 */
	public String getFormazione()
	{
		return formazione;
	}

	/**
	 * Method 'setFormazione'
	 * 
	 * @param formazione
	 */
	public void setFormazione(String formazione)
	{
		this.formazione = formazione;
	}

	/**
	 * Method 'getFulltime'
	 * 
	 * @return String
	 */
	public String getFulltime()
	{
		return fulltime;
	}

	/**
	 * Method 'setFulltime'
	 * 
	 * @param fulltime
	 */
	public void setFulltime(String fulltime)
	{
		this.fulltime = fulltime;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Tci0003Dipendentecigo)) {
			return false;
		}
		
		final Tci0003Dipendentecigo _cast = (Tci0003Dipendentecigo) _other;
		if (pr != _cast.pr) {
			return false;
		}
		
		if (iddipendente != _cast.iddipendente) {
			return false;
		}
		
		if (iddipendenteNull != _cast.iddipendenteNull) {
			return false;
		}
		
		if (commessa == null ? _cast.commessa != commessa : !commessa.equals( _cast.commessa )) {
			return false;
		}
		
		if (allocato == null ? _cast.allocato != allocato : !allocato.equals( _cast.allocato )) {
			return false;
		}
		
		if (reparto == null ? _cast.reparto != reparto : !reparto.equals( _cast.reparto )) {
			return false;
		}
		
		if (percentualeCIGO != _cast.percentualeCIGO) {
			return false;
		}
		
		if (percentualeCIGONull != _cast.percentualeCIGONull) {
			return false;
		}
		
		if (datainizio == null ? _cast.datainizio != datainizio : !datainizio.equals( _cast.datainizio )) {
			return false;
		}
		
		if (datafine == null ? _cast.datafine != datafine : !datafine.equals( _cast.datafine )) {
			return false;
		}
		
		if (datarientroanticipato == null ? _cast.datarientroanticipato != datarientroanticipato : !datarientroanticipato.equals( _cast.datarientroanticipato )) {
			return false;
		}
		
		if (formazione == null ? _cast.formazione != formazione : !formazione.equals( _cast.formazione )) {
			return false;
		}
		
		if (fulltime == null ? _cast.fulltime != fulltime : !fulltime.equals( _cast.fulltime )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + pr;
		_hashCode = 29 * _hashCode + iddipendente;
		_hashCode = 29 * _hashCode + (iddipendenteNull ? 1 : 0);
		if (commessa != null) {
			_hashCode = 29 * _hashCode + commessa.hashCode();
		}
		
		if (allocato != null) {
			_hashCode = 29 * _hashCode + allocato.hashCode();
		}
		
		if (reparto != null) {
			_hashCode = 29 * _hashCode + reparto.hashCode();
		}
		
		_hashCode = 29 * _hashCode + percentualeCIGO;
		_hashCode = 29 * _hashCode + (percentualeCIGONull ? 1 : 0);
		if (datainizio != null) {
			_hashCode = 29 * _hashCode + datainizio.hashCode();
		}
		
		if (datafine != null) {
			_hashCode = 29 * _hashCode + datafine.hashCode();
		}
		
		if (datarientroanticipato != null) {
			_hashCode = 29 * _hashCode + datarientroanticipato.hashCode();
		}
		
		if (formazione != null) {
			_hashCode = 29 * _hashCode + formazione.hashCode();
		}
		
		if (fulltime != null) {
			_hashCode = 29 * _hashCode + fulltime.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return Tci0003DipendentecigoPk
	 */
	public Tci0003DipendentecigoPk createPk()
	{
		return new Tci0003DipendentecigoPk(pr);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "comws.flau.ci.dto.Tci0003Dipendentecigo: " );
		ret.append( "pr=" + pr );
		ret.append( ", iddipendente=" + iddipendente );
		ret.append( ", commessa=" + commessa );
		ret.append( ", allocato=" + allocato );
		ret.append( ", reparto=" + reparto );
		ret.append( ", percentualeCIGO=" + percentualeCIGO );
		ret.append( ", datainizio=" + datainizio );
		ret.append( ", datafine=" + datafine );
		ret.append( ", datarientroanticipato=" + datarientroanticipato );
		ret.append( ", formazione=" + formazione );
		ret.append( ", fulltime=" + fulltime );
		return ret.toString();
	}

}
