/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package comws.flau.ci.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the tci2000_documenti table.
 */
public class Tci2000DocumentiPk implements Serializable
{
	protected int prgDoc;

	/** 
	 * This attribute represents whether the primitive attribute prgDoc is null.
	 */
	protected boolean prgDocNull;

	/** 
	 * Sets the value of prgDoc
	 */
	public void setPrgDoc(int prgDoc)
	{
		this.prgDoc = prgDoc;
	}

	/** 
	 * Gets the value of prgDoc
	 */
	public int getPrgDoc()
	{
		return prgDoc;
	}

	/**
	 * Method 'Tci2000DocumentiPk'
	 * 
	 */
	public Tci2000DocumentiPk()
	{
	}

	/**
	 * Method 'Tci2000DocumentiPk'
	 * 
	 * @param prgDoc
	 */
	public Tci2000DocumentiPk(final int prgDoc)
	{
		this.prgDoc = prgDoc;
	}

	/** 
	 * Sets the value of prgDocNull
	 */
	public void setPrgDocNull(boolean prgDocNull)
	{
		this.prgDocNull = prgDocNull;
	}

	/** 
	 * Gets the value of prgDocNull
	 */
	public boolean isPrgDocNull()
	{
		return prgDocNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Tci2000DocumentiPk)) {
			return false;
		}
		
		final Tci2000DocumentiPk _cast = (Tci2000DocumentiPk) _other;
		if (prgDoc != _cast.prgDoc) {
			return false;
		}
		
		if (prgDocNull != _cast.prgDocNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + prgDoc;
		_hashCode = 29 * _hashCode + (prgDocNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "comws.flau.ci.dto.Tci2000DocumentiPk: " );
		ret.append( "prgDoc=" + prgDoc );
		return ret.toString();
	}

}
