/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package comws.flau.ci.dto;

import comws.flau.ci.dao.*;
import comws.flau.ci.factory.*;
import comws.flau.ci.exceptions.*;
import java.io.Serializable;
import java.util.*;
import java.util.Date;

public class Tsa1010Utenza implements Serializable
{
	/** 
	 * This attribute maps to the column PRG_UTE in the tsa1010_utenza table.
	 */
	protected int prgUte;

	/** 
	 * This attribute maps to the column DES_UTE in the tsa1010_utenza table.
	 */
	protected String desUte;

	/** 
	 * This attribute maps to the column COD_FISCALE in the tsa1010_utenza table.
	 */
	protected String codFiscale;

	/** 
	 * This attribute maps to the column DES_IND_EMAIL in the tsa1010_utenza table.
	 */
	protected String desIndEmail;

	/** 
	 * This attribute maps to the column DES_IND_EMAIL_ALT in the tsa1010_utenza table.
	 */
	protected String desIndEmailAlt;

	/** 
	 * This attribute maps to the column DES_PSW in the tsa1010_utenza table.
	 */
	protected String desPsw;

	/** 
	 * This attribute maps to the column DES_FILE_LDAP in the tsa1010_utenza table.
	 */
	protected String desFileLdap;

	/** 
	 * This attribute maps to the column COD_PGM_ULT_MOV in the tsa1010_utenza table.
	 */
	protected String codPgmUltMov;

	/** 
	 * This attribute maps to the column COD_UTE_ULT_MOV in the tsa1010_utenza table.
	 */
	protected String codUteUltMov;

	/** 
	 * This attribute maps to the column DAT_ORA_ULT_MOV in the tsa1010_utenza table.
	 */
	protected Date datOraUltMov;

	/** 
	 * This attribute maps to the column FLG_VAL_UTE in the tsa1010_utenza table.
	 */
	protected String flgValUte;

	/** 
	 * This attribute maps to the column DES_COG in the tsa1010_utenza table.
	 */
	protected String desCog;

	/** 
	 * This attribute maps to the column DES_NOM in the tsa1010_utenza table.
	 */
	protected String desNom;

	/**
	 * Method 'Tsa1010Utenza'
	 * 
	 */
	public Tsa1010Utenza()
	{
	}

	/**
	 * Method 'getPrgUte'
	 * 
	 * @return int
	 */
	public int getPrgUte()
	{
		return prgUte;
	}

	/**
	 * Method 'setPrgUte'
	 * 
	 * @param prgUte
	 */
	public void setPrgUte(int prgUte)
	{
		this.prgUte = prgUte;
	}

	/**
	 * Method 'getDesUte'
	 * 
	 * @return String
	 */
	public String getDesUte()
	{
		return desUte;
	}

	/**
	 * Method 'setDesUte'
	 * 
	 * @param desUte
	 */
	public void setDesUte(String desUte)
	{
		this.desUte = desUte;
	}

	/**
	 * Method 'getCodFiscale'
	 * 
	 * @return String
	 */
	public String getCodFiscale()
	{
		return codFiscale;
	}

	/**
	 * Method 'setCodFiscale'
	 * 
	 * @param codFiscale
	 */
	public void setCodFiscale(String codFiscale)
	{
		this.codFiscale = codFiscale;
	}

	/**
	 * Method 'getDesIndEmail'
	 * 
	 * @return String
	 */
	public String getDesIndEmail()
	{
		return desIndEmail;
	}

	/**
	 * Method 'setDesIndEmail'
	 * 
	 * @param desIndEmail
	 */
	public void setDesIndEmail(String desIndEmail)
	{
		this.desIndEmail = desIndEmail;
	}

	/**
	 * Method 'getDesIndEmailAlt'
	 * 
	 * @return String
	 */
	public String getDesIndEmailAlt()
	{
		return desIndEmailAlt;
	}

	/**
	 * Method 'setDesIndEmailAlt'
	 * 
	 * @param desIndEmailAlt
	 */
	public void setDesIndEmailAlt(String desIndEmailAlt)
	{
		this.desIndEmailAlt = desIndEmailAlt;
	}

	/**
	 * Method 'getDesPsw'
	 * 
	 * @return String
	 */
	public String getDesPsw()
	{
		return desPsw;
	}

	/**
	 * Method 'setDesPsw'
	 * 
	 * @param desPsw
	 */
	public void setDesPsw(String desPsw)
	{
		this.desPsw = desPsw;
	}

	/**
	 * Method 'getDesFileLdap'
	 * 
	 * @return String
	 */
	public String getDesFileLdap()
	{
		return desFileLdap;
	}

	/**
	 * Method 'setDesFileLdap'
	 * 
	 * @param desFileLdap
	 */
	public void setDesFileLdap(String desFileLdap)
	{
		this.desFileLdap = desFileLdap;
	}

	/**
	 * Method 'getCodPgmUltMov'
	 * 
	 * @return String
	 */
	public String getCodPgmUltMov()
	{
		return codPgmUltMov;
	}

	/**
	 * Method 'setCodPgmUltMov'
	 * 
	 * @param codPgmUltMov
	 */
	public void setCodPgmUltMov(String codPgmUltMov)
	{
		this.codPgmUltMov = codPgmUltMov;
	}

	/**
	 * Method 'getCodUteUltMov'
	 * 
	 * @return String
	 */
	public String getCodUteUltMov()
	{
		return codUteUltMov;
	}

	/**
	 * Method 'setCodUteUltMov'
	 * 
	 * @param codUteUltMov
	 */
	public void setCodUteUltMov(String codUteUltMov)
	{
		this.codUteUltMov = codUteUltMov;
	}

	/**
	 * Method 'getDatOraUltMov'
	 * 
	 * @return Date
	 */
	public Date getDatOraUltMov()
	{
		return datOraUltMov;
	}

	/**
	 * Method 'setDatOraUltMov'
	 * 
	 * @param datOraUltMov
	 */
	public void setDatOraUltMov(Date datOraUltMov)
	{
		this.datOraUltMov = datOraUltMov;
	}

	/**
	 * Method 'getFlgValUte'
	 * 
	 * @return String
	 */
	public String getFlgValUte()
	{
		return flgValUte;
	}

	/**
	 * Method 'setFlgValUte'
	 * 
	 * @param flgValUte
	 */
	public void setFlgValUte(String flgValUte)
	{
		this.flgValUte = flgValUte;
	}

	/**
	 * Method 'getDesCog'
	 * 
	 * @return String
	 */
	public String getDesCog()
	{
		return desCog;
	}

	/**
	 * Method 'setDesCog'
	 * 
	 * @param desCog
	 */
	public void setDesCog(String desCog)
	{
		this.desCog = desCog;
	}

	/**
	 * Method 'getDesNom'
	 * 
	 * @return String
	 */
	public String getDesNom()
	{
		return desNom;
	}

	/**
	 * Method 'setDesNom'
	 * 
	 * @param desNom
	 */
	public void setDesNom(String desNom)
	{
		this.desNom = desNom;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Tsa1010Utenza)) {
			return false;
		}
		
		final Tsa1010Utenza _cast = (Tsa1010Utenza) _other;
		if (prgUte != _cast.prgUte) {
			return false;
		}
		
		if (desUte == null ? _cast.desUte != desUte : !desUte.equals( _cast.desUte )) {
			return false;
		}
		
		if (codFiscale == null ? _cast.codFiscale != codFiscale : !codFiscale.equals( _cast.codFiscale )) {
			return false;
		}
		
		if (desIndEmail == null ? _cast.desIndEmail != desIndEmail : !desIndEmail.equals( _cast.desIndEmail )) {
			return false;
		}
		
		if (desIndEmailAlt == null ? _cast.desIndEmailAlt != desIndEmailAlt : !desIndEmailAlt.equals( _cast.desIndEmailAlt )) {
			return false;
		}
		
		if (desPsw == null ? _cast.desPsw != desPsw : !desPsw.equals( _cast.desPsw )) {
			return false;
		}
		
		if (desFileLdap == null ? _cast.desFileLdap != desFileLdap : !desFileLdap.equals( _cast.desFileLdap )) {
			return false;
		}
		
		if (codPgmUltMov == null ? _cast.codPgmUltMov != codPgmUltMov : !codPgmUltMov.equals( _cast.codPgmUltMov )) {
			return false;
		}
		
		if (codUteUltMov == null ? _cast.codUteUltMov != codUteUltMov : !codUteUltMov.equals( _cast.codUteUltMov )) {
			return false;
		}
		
		if (datOraUltMov == null ? _cast.datOraUltMov != datOraUltMov : !datOraUltMov.equals( _cast.datOraUltMov )) {
			return false;
		}
		
		if (flgValUte == null ? _cast.flgValUte != flgValUte : !flgValUte.equals( _cast.flgValUte )) {
			return false;
		}
		
		if (desCog == null ? _cast.desCog != desCog : !desCog.equals( _cast.desCog )) {
			return false;
		}
		
		if (desNom == null ? _cast.desNom != desNom : !desNom.equals( _cast.desNom )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + prgUte;
		if (desUte != null) {
			_hashCode = 29 * _hashCode + desUte.hashCode();
		}
		
		if (codFiscale != null) {
			_hashCode = 29 * _hashCode + codFiscale.hashCode();
		}
		
		if (desIndEmail != null) {
			_hashCode = 29 * _hashCode + desIndEmail.hashCode();
		}
		
		if (desIndEmailAlt != null) {
			_hashCode = 29 * _hashCode + desIndEmailAlt.hashCode();
		}
		
		if (desPsw != null) {
			_hashCode = 29 * _hashCode + desPsw.hashCode();
		}
		
		if (desFileLdap != null) {
			_hashCode = 29 * _hashCode + desFileLdap.hashCode();
		}
		
		if (codPgmUltMov != null) {
			_hashCode = 29 * _hashCode + codPgmUltMov.hashCode();
		}
		
		if (codUteUltMov != null) {
			_hashCode = 29 * _hashCode + codUteUltMov.hashCode();
		}
		
		if (datOraUltMov != null) {
			_hashCode = 29 * _hashCode + datOraUltMov.hashCode();
		}
		
		if (flgValUte != null) {
			_hashCode = 29 * _hashCode + flgValUte.hashCode();
		}
		
		if (desCog != null) {
			_hashCode = 29 * _hashCode + desCog.hashCode();
		}
		
		if (desNom != null) {
			_hashCode = 29 * _hashCode + desNom.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return Tsa1010UtenzaPk
	 */
	public Tsa1010UtenzaPk createPk()
	{
		return new Tsa1010UtenzaPk(prgUte);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "comws.flau.ci.dto.Tsa1010Utenza: " );
		ret.append( "prgUte=" + prgUte );
		ret.append( ", desUte=" + desUte );
		ret.append( ", codFiscale=" + codFiscale );
		ret.append( ", desIndEmail=" + desIndEmail );
		ret.append( ", desIndEmailAlt=" + desIndEmailAlt );
		ret.append( ", desPsw=" + desPsw );
		ret.append( ", desFileLdap=" + desFileLdap );
		ret.append( ", codPgmUltMov=" + codPgmUltMov );
		ret.append( ", codUteUltMov=" + codUteUltMov );
		ret.append( ", datOraUltMov=" + datOraUltMov );
		ret.append( ", flgValUte=" + flgValUte );
		ret.append( ", desCog=" + desCog );
		ret.append( ", desNom=" + desNom );
		return ret.toString();
	}

}
