/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package comws.flau.ci.dto;

import comws.flau.ci.dao.*;
import comws.flau.ci.factory.*;
import comws.flau.ci.exceptions.*;
import java.io.Serializable;
import java.util.*;
import java.util.Date;

public class Tsa1005Contutenze implements Serializable
{
	/** 
	 * This attribute maps to the column DES_VAL_CNT in the tsa1005_contutenze table.
	 */
	protected String desValCnt;

	/** 
	 * This attribute maps to the column ORD_CNT in the tsa1005_contutenze table.
	 */
	protected int ordCnt;

	/** 
	 * This attribute maps to the column PRG_CNT in the tsa1005_contutenze table.
	 */
	protected int prgCnt;

	/** 
	 * This attribute maps to the column DAT_ORA_ULT_MOV in the tsa1005_contutenze table.
	 */
	protected Date datOraUltMov;

	/** 
	 * This attribute maps to the column COD_UTE_ULT_MOV in the tsa1005_contutenze table.
	 */
	protected String codUteUltMov;

	/** 
	 * This attribute maps to the column COD_PGM_ULT_MOV in the tsa1005_contutenze table.
	 */
	protected String codPgmUltMov;

	/** 
	 * This attribute maps to the column PRG_PRF_FGL in the tsa1005_contutenze table.
	 */
	protected int prgPrfFgl;

	/** 
	 * This attribute maps to the column PRG_UTE in the tsa1005_contutenze table.
	 */
	protected int prgUte;

	/** 
	 * This attribute maps to the column PRG_PRF_PDR in the tsa1005_contutenze table.
	 */
	protected int prgPrfPdr;

	/** 
	 * This attribute maps to the column FLG_ABL in the tsa1005_contutenze table.
	 */
	protected String flgAbl;

	/** 
	 * This attribute maps to the column PRG_APP in the tsa1005_contutenze table.
	 */
	protected int prgApp;

	/** 
	 * This attribute maps to the column FLG_CAN in the tsa1005_contutenze table.
	 */
	protected String flgCan;

	/** 
	 * This attribute maps to the column FLG_TRA_DAT in the tsa1005_contutenze table.
	 */
	protected String flgTraDat;

	/**
	 * Method 'Tsa1005Contutenze'
	 * 
	 */
	public Tsa1005Contutenze()
	{
	}

	/**
	 * Method 'getDesValCnt'
	 * 
	 * @return String
	 */
	public String getDesValCnt()
	{
		return desValCnt;
	}

	/**
	 * Method 'setDesValCnt'
	 * 
	 * @param desValCnt
	 */
	public void setDesValCnt(String desValCnt)
	{
		this.desValCnt = desValCnt;
	}

	/**
	 * Method 'getOrdCnt'
	 * 
	 * @return int
	 */
	public int getOrdCnt()
	{
		return ordCnt;
	}

	/**
	 * Method 'setOrdCnt'
	 * 
	 * @param ordCnt
	 */
	public void setOrdCnt(int ordCnt)
	{
		this.ordCnt = ordCnt;
	}

	/**
	 * Method 'getPrgCnt'
	 * 
	 * @return int
	 */
	public int getPrgCnt()
	{
		return prgCnt;
	}

	/**
	 * Method 'setPrgCnt'
	 * 
	 * @param prgCnt
	 */
	public void setPrgCnt(int prgCnt)
	{
		this.prgCnt = prgCnt;
	}

	/**
	 * Method 'getDatOraUltMov'
	 * 
	 * @return Date
	 */
	public Date getDatOraUltMov()
	{
		return datOraUltMov;
	}

	/**
	 * Method 'setDatOraUltMov'
	 * 
	 * @param datOraUltMov
	 */
	public void setDatOraUltMov(Date datOraUltMov)
	{
		this.datOraUltMov = datOraUltMov;
	}

	/**
	 * Method 'getCodUteUltMov'
	 * 
	 * @return String
	 */
	public String getCodUteUltMov()
	{
		return codUteUltMov;
	}

	/**
	 * Method 'setCodUteUltMov'
	 * 
	 * @param codUteUltMov
	 */
	public void setCodUteUltMov(String codUteUltMov)
	{
		this.codUteUltMov = codUteUltMov;
	}

	/**
	 * Method 'getCodPgmUltMov'
	 * 
	 * @return String
	 */
	public String getCodPgmUltMov()
	{
		return codPgmUltMov;
	}

	/**
	 * Method 'setCodPgmUltMov'
	 * 
	 * @param codPgmUltMov
	 */
	public void setCodPgmUltMov(String codPgmUltMov)
	{
		this.codPgmUltMov = codPgmUltMov;
	}

	/**
	 * Method 'getPrgPrfFgl'
	 * 
	 * @return int
	 */
	public int getPrgPrfFgl()
	{
		return prgPrfFgl;
	}

	/**
	 * Method 'setPrgPrfFgl'
	 * 
	 * @param prgPrfFgl
	 */
	public void setPrgPrfFgl(int prgPrfFgl)
	{
		this.prgPrfFgl = prgPrfFgl;
	}

	/**
	 * Method 'getPrgUte'
	 * 
	 * @return int
	 */
	public int getPrgUte()
	{
		return prgUte;
	}

	/**
	 * Method 'setPrgUte'
	 * 
	 * @param prgUte
	 */
	public void setPrgUte(int prgUte)
	{
		this.prgUte = prgUte;
	}

	/**
	 * Method 'getPrgPrfPdr'
	 * 
	 * @return int
	 */
	public int getPrgPrfPdr()
	{
		return prgPrfPdr;
	}

	/**
	 * Method 'setPrgPrfPdr'
	 * 
	 * @param prgPrfPdr
	 */
	public void setPrgPrfPdr(int prgPrfPdr)
	{
		this.prgPrfPdr = prgPrfPdr;
	}

	/**
	 * Method 'getFlgAbl'
	 * 
	 * @return String
	 */
	public String getFlgAbl()
	{
		return flgAbl;
	}

	/**
	 * Method 'setFlgAbl'
	 * 
	 * @param flgAbl
	 */
	public void setFlgAbl(String flgAbl)
	{
		this.flgAbl = flgAbl;
	}

	/**
	 * Method 'getPrgApp'
	 * 
	 * @return int
	 */
	public int getPrgApp()
	{
		return prgApp;
	}

	/**
	 * Method 'setPrgApp'
	 * 
	 * @param prgApp
	 */
	public void setPrgApp(int prgApp)
	{
		this.prgApp = prgApp;
	}

	/**
	 * Method 'getFlgCan'
	 * 
	 * @return String
	 */
	public String getFlgCan()
	{
		return flgCan;
	}

	/**
	 * Method 'setFlgCan'
	 * 
	 * @param flgCan
	 */
	public void setFlgCan(String flgCan)
	{
		this.flgCan = flgCan;
	}

	/**
	 * Method 'getFlgTraDat'
	 * 
	 * @return String
	 */
	public String getFlgTraDat()
	{
		return flgTraDat;
	}

	/**
	 * Method 'setFlgTraDat'
	 * 
	 * @param flgTraDat
	 */
	public void setFlgTraDat(String flgTraDat)
	{
		this.flgTraDat = flgTraDat;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Tsa1005Contutenze)) {
			return false;
		}
		
		final Tsa1005Contutenze _cast = (Tsa1005Contutenze) _other;
		if (desValCnt == null ? _cast.desValCnt != desValCnt : !desValCnt.equals( _cast.desValCnt )) {
			return false;
		}
		
		if (ordCnt != _cast.ordCnt) {
			return false;
		}
		
		if (prgCnt != _cast.prgCnt) {
			return false;
		}
		
		if (datOraUltMov == null ? _cast.datOraUltMov != datOraUltMov : !datOraUltMov.equals( _cast.datOraUltMov )) {
			return false;
		}
		
		if (codUteUltMov == null ? _cast.codUteUltMov != codUteUltMov : !codUteUltMov.equals( _cast.codUteUltMov )) {
			return false;
		}
		
		if (codPgmUltMov == null ? _cast.codPgmUltMov != codPgmUltMov : !codPgmUltMov.equals( _cast.codPgmUltMov )) {
			return false;
		}
		
		if (prgPrfFgl != _cast.prgPrfFgl) {
			return false;
		}
		
		if (prgUte != _cast.prgUte) {
			return false;
		}
		
		if (prgPrfPdr != _cast.prgPrfPdr) {
			return false;
		}
		
		if (flgAbl == null ? _cast.flgAbl != flgAbl : !flgAbl.equals( _cast.flgAbl )) {
			return false;
		}
		
		if (prgApp != _cast.prgApp) {
			return false;
		}
		
		if (flgCan == null ? _cast.flgCan != flgCan : !flgCan.equals( _cast.flgCan )) {
			return false;
		}
		
		if (flgTraDat == null ? _cast.flgTraDat != flgTraDat : !flgTraDat.equals( _cast.flgTraDat )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		if (desValCnt != null) {
			_hashCode = 29 * _hashCode + desValCnt.hashCode();
		}
		
		_hashCode = 29 * _hashCode + ordCnt;
		_hashCode = 29 * _hashCode + prgCnt;
		if (datOraUltMov != null) {
			_hashCode = 29 * _hashCode + datOraUltMov.hashCode();
		}
		
		if (codUteUltMov != null) {
			_hashCode = 29 * _hashCode + codUteUltMov.hashCode();
		}
		
		if (codPgmUltMov != null) {
			_hashCode = 29 * _hashCode + codPgmUltMov.hashCode();
		}
		
		_hashCode = 29 * _hashCode + prgPrfFgl;
		_hashCode = 29 * _hashCode + prgUte;
		_hashCode = 29 * _hashCode + prgPrfPdr;
		if (flgAbl != null) {
			_hashCode = 29 * _hashCode + flgAbl.hashCode();
		}
		
		_hashCode = 29 * _hashCode + prgApp;
		if (flgCan != null) {
			_hashCode = 29 * _hashCode + flgCan.hashCode();
		}
		
		if (flgTraDat != null) {
			_hashCode = 29 * _hashCode + flgTraDat.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return Tsa1005ContutenzePk
	 */
	public Tsa1005ContutenzePk createPk()
	{
		return new Tsa1005ContutenzePk(prgCnt, prgUte, prgPrfFgl, prgPrfPdr, prgApp, ordCnt);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "comws.flau.ci.dto.Tsa1005Contutenze: " );
		ret.append( "desValCnt=" + desValCnt );
		ret.append( ", ordCnt=" + ordCnt );
		ret.append( ", prgCnt=" + prgCnt );
		ret.append( ", datOraUltMov=" + datOraUltMov );
		ret.append( ", codUteUltMov=" + codUteUltMov );
		ret.append( ", codPgmUltMov=" + codPgmUltMov );
		ret.append( ", prgPrfFgl=" + prgPrfFgl );
		ret.append( ", prgUte=" + prgUte );
		ret.append( ", prgPrfPdr=" + prgPrfPdr );
		ret.append( ", flgAbl=" + flgAbl );
		ret.append( ", prgApp=" + prgApp );
		ret.append( ", flgCan=" + flgCan );
		ret.append( ", flgTraDat=" + flgTraDat );
		return ret.toString();
	}

}
