/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package comws.flau.ci.dto;

import comws.flau.ci.dao.*;
import comws.flau.ci.factory.*;
import comws.flau.ci.exceptions.*;
import java.io.Serializable;
import java.util.*;
import java.util.Date;

public class VciElenco001 implements Serializable
{
	/** 
	 * This attribute maps to the column PRG_UTE in the vci_elenco001 table.
	 */
	protected int prgUte;

	/** 
	 * This attribute maps to the column DES_UTE in the vci_elenco001 table.
	 */
	protected String desUte;

	/** 
	 * This attribute maps to the column COD_FISCALE in the vci_elenco001 table.
	 */
	protected String codFiscale;

	/** 
	 * This attribute maps to the column DES_IND_EMAIL in the vci_elenco001 table.
	 */
	protected String desIndEmail;

	/** 
	 * This attribute maps to the column DES_IND_EMAIL_ALT in the vci_elenco001 table.
	 */
	protected String desIndEmailAlt;

	/** 
	 * This attribute maps to the column DES_PSW in the vci_elenco001 table.
	 */
	protected String desPsw;

	/** 
	 * This attribute maps to the column DES_FILE_LDAP in the vci_elenco001 table.
	 */
	protected String desFileLdap;

	/** 
	 * This attribute maps to the column COD_PGM_ULT_MOV in the vci_elenco001 table.
	 */
	protected String codPgmUltMov;

	/** 
	 * This attribute maps to the column COD_UTE_ULT_MOV in the vci_elenco001 table.
	 */
	protected String codUteUltMov;

	/** 
	 * This attribute maps to the column DAT_ORA_ULT_MOV in the vci_elenco001 table.
	 */
	protected Date datOraUltMov;

	/** 
	 * This attribute maps to the column FLG_VAL_UTE in the vci_elenco001 table.
	 */
	protected String flgValUte;

	/** 
	 * This attribute maps to the column DES_COG in the vci_elenco001 table.
	 */
	protected String desCog;

	/** 
	 * This attribute maps to the column DES_NOM in the vci_elenco001 table.
	 */
	protected String desNom;

	/** 
	 * This attribute maps to the column pr in the vci_elenco001 table.
	 */
	protected int pr;

	/** 
	 * This attribute maps to the column iddipendente in the vci_elenco001 table.
	 */
	protected int iddipendente;

	/** 
	 * This attribute represents whether the primitive attribute iddipendente is null.
	 */
	protected boolean iddipendenteNull = true;

	/** 
	 * This attribute maps to the column Commessa in the vci_elenco001 table.
	 */
	protected String commessa;

	/** 
	 * This attribute maps to the column allocato in the vci_elenco001 table.
	 */
	protected String allocato;

	/** 
	 * This attribute maps to the column reparto in the vci_elenco001 table.
	 */
	protected String reparto;

	/** 
	 * This attribute maps to the column PercentualeCIGO in the vci_elenco001 table.
	 */
	protected int percentualeCIGO;

	/** 
	 * This attribute represents whether the primitive attribute percentualeCIGO is null.
	 */
	protected boolean percentualeCIGONull = true;

	/** 
	 * This attribute maps to the column datainizio in the vci_elenco001 table.
	 */
	protected Date datainizio;

	/** 
	 * This attribute maps to the column datafine in the vci_elenco001 table.
	 */
	protected Date datafine;

	/** 
	 * This attribute maps to the column datarientroanticipato in the vci_elenco001 table.
	 */
	protected Date datarientroanticipato;

	/** 
	 * This attribute maps to the column formazione in the vci_elenco001 table.
	 */
	protected String formazione;

	/** 
	 * This attribute maps to the column fulltime in the vci_elenco001 table.
	 */
	protected String fulltime;

	/**
	 * Method 'VciElenco001'
	 * 
	 */
	public VciElenco001()
	{
	}

	/**
	 * Method 'getPrgUte'
	 * 
	 * @return int
	 */
	public int getPrgUte()
	{
		return prgUte;
	}

	/**
	 * Method 'setPrgUte'
	 * 
	 * @param prgUte
	 */
	public void setPrgUte(int prgUte)
	{
		this.prgUte = prgUte;
	}

	/**
	 * Method 'getDesUte'
	 * 
	 * @return String
	 */
	public String getDesUte()
	{
		return desUte;
	}

	/**
	 * Method 'setDesUte'
	 * 
	 * @param desUte
	 */
	public void setDesUte(String desUte)
	{
		this.desUte = desUte;
	}

	/**
	 * Method 'getCodFiscale'
	 * 
	 * @return String
	 */
	public String getCodFiscale()
	{
		return codFiscale;
	}

	/**
	 * Method 'setCodFiscale'
	 * 
	 * @param codFiscale
	 */
	public void setCodFiscale(String codFiscale)
	{
		this.codFiscale = codFiscale;
	}

	/**
	 * Method 'getDesIndEmail'
	 * 
	 * @return String
	 */
	public String getDesIndEmail()
	{
		return desIndEmail;
	}

	/**
	 * Method 'setDesIndEmail'
	 * 
	 * @param desIndEmail
	 */
	public void setDesIndEmail(String desIndEmail)
	{
		this.desIndEmail = desIndEmail;
	}

	/**
	 * Method 'getDesIndEmailAlt'
	 * 
	 * @return String
	 */
	public String getDesIndEmailAlt()
	{
		return desIndEmailAlt;
	}

	/**
	 * Method 'setDesIndEmailAlt'
	 * 
	 * @param desIndEmailAlt
	 */
	public void setDesIndEmailAlt(String desIndEmailAlt)
	{
		this.desIndEmailAlt = desIndEmailAlt;
	}

	/**
	 * Method 'getDesPsw'
	 * 
	 * @return String
	 */
	public String getDesPsw()
	{
		return desPsw;
	}

	/**
	 * Method 'setDesPsw'
	 * 
	 * @param desPsw
	 */
	public void setDesPsw(String desPsw)
	{
		this.desPsw = desPsw;
	}

	/**
	 * Method 'getDesFileLdap'
	 * 
	 * @return String
	 */
	public String getDesFileLdap()
	{
		return desFileLdap;
	}

	/**
	 * Method 'setDesFileLdap'
	 * 
	 * @param desFileLdap
	 */
	public void setDesFileLdap(String desFileLdap)
	{
		this.desFileLdap = desFileLdap;
	}

	/**
	 * Method 'getCodPgmUltMov'
	 * 
	 * @return String
	 */
	public String getCodPgmUltMov()
	{
		return codPgmUltMov;
	}

	/**
	 * Method 'setCodPgmUltMov'
	 * 
	 * @param codPgmUltMov
	 */
	public void setCodPgmUltMov(String codPgmUltMov)
	{
		this.codPgmUltMov = codPgmUltMov;
	}

	/**
	 * Method 'getCodUteUltMov'
	 * 
	 * @return String
	 */
	public String getCodUteUltMov()
	{
		return codUteUltMov;
	}

	/**
	 * Method 'setCodUteUltMov'
	 * 
	 * @param codUteUltMov
	 */
	public void setCodUteUltMov(String codUteUltMov)
	{
		this.codUteUltMov = codUteUltMov;
	}

	/**
	 * Method 'getDatOraUltMov'
	 * 
	 * @return Date
	 */
	public Date getDatOraUltMov()
	{
		return datOraUltMov;
	}

	/**
	 * Method 'setDatOraUltMov'
	 * 
	 * @param datOraUltMov
	 */
	public void setDatOraUltMov(Date datOraUltMov)
	{
		this.datOraUltMov = datOraUltMov;
	}

	/**
	 * Method 'getFlgValUte'
	 * 
	 * @return String
	 */
	public String getFlgValUte()
	{
		return flgValUte;
	}

	/**
	 * Method 'setFlgValUte'
	 * 
	 * @param flgValUte
	 */
	public void setFlgValUte(String flgValUte)
	{
		this.flgValUte = flgValUte;
	}

	/**
	 * Method 'getDesCog'
	 * 
	 * @return String
	 */
	public String getDesCog()
	{
		return desCog;
	}

	/**
	 * Method 'setDesCog'
	 * 
	 * @param desCog
	 */
	public void setDesCog(String desCog)
	{
		this.desCog = desCog;
	}

	/**
	 * Method 'getDesNom'
	 * 
	 * @return String
	 */
	public String getDesNom()
	{
		return desNom;
	}

	/**
	 * Method 'setDesNom'
	 * 
	 * @param desNom
	 */
	public void setDesNom(String desNom)
	{
		this.desNom = desNom;
	}

	/**
	 * Method 'getPr'
	 * 
	 * @return int
	 */
	public int getPr()
	{
		return pr;
	}

	/**
	 * Method 'setPr'
	 * 
	 * @param pr
	 */
	public void setPr(int pr)
	{
		this.pr = pr;
	}

	/**
	 * Method 'getIddipendente'
	 * 
	 * @return int
	 */
	public int getIddipendente()
	{
		return iddipendente;
	}

	/**
	 * Method 'setIddipendente'
	 * 
	 * @param iddipendente
	 */
	public void setIddipendente(int iddipendente)
	{
		this.iddipendente = iddipendente;
		this.iddipendenteNull = false;
	}

	/**
	 * Method 'setIddipendenteNull'
	 * 
	 * @param value
	 */
	public void setIddipendenteNull(boolean value)
	{
		this.iddipendenteNull = value;
	}

	/**
	 * Method 'isIddipendenteNull'
	 * 
	 * @return boolean
	 */
	public boolean isIddipendenteNull()
	{
		return iddipendenteNull;
	}

	/**
	 * Method 'getCommessa'
	 * 
	 * @return String
	 */
	public String getCommessa()
	{
		return commessa;
	}

	/**
	 * Method 'setCommessa'
	 * 
	 * @param commessa
	 */
	public void setCommessa(String commessa)
	{
		this.commessa = commessa;
	}

	/**
	 * Method 'getAllocato'
	 * 
	 * @return String
	 */
	public String getAllocato()
	{
		return allocato;
	}

	/**
	 * Method 'setAllocato'
	 * 
	 * @param allocato
	 */
	public void setAllocato(String allocato)
	{
		this.allocato = allocato;
	}

	/**
	 * Method 'getReparto'
	 * 
	 * @return String
	 */
	public String getReparto()
	{
		return reparto;
	}

	/**
	 * Method 'setReparto'
	 * 
	 * @param reparto
	 */
	public void setReparto(String reparto)
	{
		this.reparto = reparto;
	}

	/**
	 * Method 'getPercentualeCIGO'
	 * 
	 * @return int
	 */
	public int getPercentualeCIGO()
	{
		return percentualeCIGO;
	}

	/**
	 * Method 'setPercentualeCIGO'
	 * 
	 * @param percentualeCIGO
	 */
	public void setPercentualeCIGO(int percentualeCIGO)
	{
		this.percentualeCIGO = percentualeCIGO;
		this.percentualeCIGONull = false;
	}

	/**
	 * Method 'setPercentualeCIGONull'
	 * 
	 * @param value
	 */
	public void setPercentualeCIGONull(boolean value)
	{
		this.percentualeCIGONull = value;
	}

	/**
	 * Method 'isPercentualeCIGONull'
	 * 
	 * @return boolean
	 */
	public boolean isPercentualeCIGONull()
	{
		return percentualeCIGONull;
	}

	/**
	 * Method 'getDatainizio'
	 * 
	 * @return Date
	 */
	public Date getDatainizio()
	{
		return datainizio;
	}

	/**
	 * Method 'setDatainizio'
	 * 
	 * @param datainizio
	 */
	public void setDatainizio(Date datainizio)
	{
		this.datainizio = datainizio;
	}

	/**
	 * Method 'getDatafine'
	 * 
	 * @return Date
	 */
	public Date getDatafine()
	{
		return datafine;
	}

	/**
	 * Method 'setDatafine'
	 * 
	 * @param datafine
	 */
	public void setDatafine(Date datafine)
	{
		this.datafine = datafine;
	}

	/**
	 * Method 'getDatarientroanticipato'
	 * 
	 * @return Date
	 */
	public Date getDatarientroanticipato()
	{
		return datarientroanticipato;
	}

	/**
	 * Method 'setDatarientroanticipato'
	 * 
	 * @param datarientroanticipato
	 */
	public void setDatarientroanticipato(Date datarientroanticipato)
	{
		this.datarientroanticipato = datarientroanticipato;
	}

	/**
	 * Method 'getFormazione'
	 * 
	 * @return String
	 */
	public String getFormazione()
	{
		return formazione;
	}

	/**
	 * Method 'setFormazione'
	 * 
	 * @param formazione
	 */
	public void setFormazione(String formazione)
	{
		this.formazione = formazione;
	}

	/**
	 * Method 'getFulltime'
	 * 
	 * @return String
	 */
	public String getFulltime()
	{
		return fulltime;
	}

	/**
	 * Method 'setFulltime'
	 * 
	 * @param fulltime
	 */
	public void setFulltime(String fulltime)
	{
		this.fulltime = fulltime;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof VciElenco001)) {
			return false;
		}
		
		final VciElenco001 _cast = (VciElenco001) _other;
		if (prgUte != _cast.prgUte) {
			return false;
		}
		
		if (desUte == null ? _cast.desUte != desUte : !desUte.equals( _cast.desUte )) {
			return false;
		}
		
		if (codFiscale == null ? _cast.codFiscale != codFiscale : !codFiscale.equals( _cast.codFiscale )) {
			return false;
		}
		
		if (desIndEmail == null ? _cast.desIndEmail != desIndEmail : !desIndEmail.equals( _cast.desIndEmail )) {
			return false;
		}
		
		if (desIndEmailAlt == null ? _cast.desIndEmailAlt != desIndEmailAlt : !desIndEmailAlt.equals( _cast.desIndEmailAlt )) {
			return false;
		}
		
		if (desPsw == null ? _cast.desPsw != desPsw : !desPsw.equals( _cast.desPsw )) {
			return false;
		}
		
		if (desFileLdap == null ? _cast.desFileLdap != desFileLdap : !desFileLdap.equals( _cast.desFileLdap )) {
			return false;
		}
		
		if (codPgmUltMov == null ? _cast.codPgmUltMov != codPgmUltMov : !codPgmUltMov.equals( _cast.codPgmUltMov )) {
			return false;
		}
		
		if (codUteUltMov == null ? _cast.codUteUltMov != codUteUltMov : !codUteUltMov.equals( _cast.codUteUltMov )) {
			return false;
		}
		
		if (datOraUltMov == null ? _cast.datOraUltMov != datOraUltMov : !datOraUltMov.equals( _cast.datOraUltMov )) {
			return false;
		}
		
		if (flgValUte == null ? _cast.flgValUte != flgValUte : !flgValUte.equals( _cast.flgValUte )) {
			return false;
		}
		
		if (desCog == null ? _cast.desCog != desCog : !desCog.equals( _cast.desCog )) {
			return false;
		}
		
		if (desNom == null ? _cast.desNom != desNom : !desNom.equals( _cast.desNom )) {
			return false;
		}
		
		if (pr != _cast.pr) {
			return false;
		}
		
		if (iddipendente != _cast.iddipendente) {
			return false;
		}
		
		if (iddipendenteNull != _cast.iddipendenteNull) {
			return false;
		}
		
		if (commessa == null ? _cast.commessa != commessa : !commessa.equals( _cast.commessa )) {
			return false;
		}
		
		if (allocato == null ? _cast.allocato != allocato : !allocato.equals( _cast.allocato )) {
			return false;
		}
		
		if (reparto == null ? _cast.reparto != reparto : !reparto.equals( _cast.reparto )) {
			return false;
		}
		
		if (percentualeCIGO != _cast.percentualeCIGO) {
			return false;
		}
		
		if (percentualeCIGONull != _cast.percentualeCIGONull) {
			return false;
		}
		
		if (datainizio == null ? _cast.datainizio != datainizio : !datainizio.equals( _cast.datainizio )) {
			return false;
		}
		
		if (datafine == null ? _cast.datafine != datafine : !datafine.equals( _cast.datafine )) {
			return false;
		}
		
		if (datarientroanticipato == null ? _cast.datarientroanticipato != datarientroanticipato : !datarientroanticipato.equals( _cast.datarientroanticipato )) {
			return false;
		}
		
		if (formazione == null ? _cast.formazione != formazione : !formazione.equals( _cast.formazione )) {
			return false;
		}
		
		if (fulltime == null ? _cast.fulltime != fulltime : !fulltime.equals( _cast.fulltime )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + prgUte;
		if (desUte != null) {
			_hashCode = 29 * _hashCode + desUte.hashCode();
		}
		
		if (codFiscale != null) {
			_hashCode = 29 * _hashCode + codFiscale.hashCode();
		}
		
		if (desIndEmail != null) {
			_hashCode = 29 * _hashCode + desIndEmail.hashCode();
		}
		
		if (desIndEmailAlt != null) {
			_hashCode = 29 * _hashCode + desIndEmailAlt.hashCode();
		}
		
		if (desPsw != null) {
			_hashCode = 29 * _hashCode + desPsw.hashCode();
		}
		
		if (desFileLdap != null) {
			_hashCode = 29 * _hashCode + desFileLdap.hashCode();
		}
		
		if (codPgmUltMov != null) {
			_hashCode = 29 * _hashCode + codPgmUltMov.hashCode();
		}
		
		if (codUteUltMov != null) {
			_hashCode = 29 * _hashCode + codUteUltMov.hashCode();
		}
		
		if (datOraUltMov != null) {
			_hashCode = 29 * _hashCode + datOraUltMov.hashCode();
		}
		
		if (flgValUte != null) {
			_hashCode = 29 * _hashCode + flgValUte.hashCode();
		}
		
		if (desCog != null) {
			_hashCode = 29 * _hashCode + desCog.hashCode();
		}
		
		if (desNom != null) {
			_hashCode = 29 * _hashCode + desNom.hashCode();
		}
		
		_hashCode = 29 * _hashCode + pr;
		_hashCode = 29 * _hashCode + iddipendente;
		_hashCode = 29 * _hashCode + (iddipendenteNull ? 1 : 0);
		if (commessa != null) {
			_hashCode = 29 * _hashCode + commessa.hashCode();
		}
		
		if (allocato != null) {
			_hashCode = 29 * _hashCode + allocato.hashCode();
		}
		
		if (reparto != null) {
			_hashCode = 29 * _hashCode + reparto.hashCode();
		}
		
		_hashCode = 29 * _hashCode + percentualeCIGO;
		_hashCode = 29 * _hashCode + (percentualeCIGONull ? 1 : 0);
		if (datainizio != null) {
			_hashCode = 29 * _hashCode + datainizio.hashCode();
		}
		
		if (datafine != null) {
			_hashCode = 29 * _hashCode + datafine.hashCode();
		}
		
		if (datarientroanticipato != null) {
			_hashCode = 29 * _hashCode + datarientroanticipato.hashCode();
		}
		
		if (formazione != null) {
			_hashCode = 29 * _hashCode + formazione.hashCode();
		}
		
		if (fulltime != null) {
			_hashCode = 29 * _hashCode + fulltime.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "comws.flau.ci.dto.VciElenco001: " );
		ret.append( "prgUte=" + prgUte );
		ret.append( ", desUte=" + desUte );
		ret.append( ", codFiscale=" + codFiscale );
		ret.append( ", desIndEmail=" + desIndEmail );
		ret.append( ", desIndEmailAlt=" + desIndEmailAlt );
		ret.append( ", desPsw=" + desPsw );
		ret.append( ", desFileLdap=" + desFileLdap );
		ret.append( ", codPgmUltMov=" + codPgmUltMov );
		ret.append( ", codUteUltMov=" + codUteUltMov );
		ret.append( ", datOraUltMov=" + datOraUltMov );
		ret.append( ", flgValUte=" + flgValUte );
		ret.append( ", desCog=" + desCog );
		ret.append( ", desNom=" + desNom );
		ret.append( ", pr=" + pr );
		ret.append( ", iddipendente=" + iddipendente );
		ret.append( ", commessa=" + commessa );
		ret.append( ", allocato=" + allocato );
		ret.append( ", reparto=" + reparto );
		ret.append( ", percentualeCIGO=" + percentualeCIGO );
		ret.append( ", datainizio=" + datainizio );
		ret.append( ", datafine=" + datafine );
		ret.append( ", datarientroanticipato=" + datarientroanticipato );
		ret.append( ", formazione=" + formazione );
		ret.append( ", fulltime=" + fulltime );
		return ret.toString();
	}

}
