/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package comws.flau.ci.dto;

import comws.flau.ci.dao.*;
import comws.flau.ci.factory.*;
import comws.flau.ci.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class Vsa1003Uteprofili implements Serializable
{
	/** 
	 * This attribute maps to the column PRG_APP in the vsa1003_uteprofili table.
	 */
	protected int prgApp;

	/** 
	 * This attribute maps to the column PRG_UTE in the vsa1003_uteprofili table.
	 */
	protected int prgUte;

	/** 
	 * This attribute maps to the column PRG_PRF_PDR in the vsa1003_uteprofili table.
	 */
	protected int prgPrfPdr;

	/** 
	 * This attribute maps to the column PRG_PRF_FGL in the vsa1003_uteprofili table.
	 */
	protected int prgPrfFgl;

	/** 
	 * This attribute maps to the column DES_PRF_PDR in the vsa1003_uteprofili table.
	 */
	protected String desPrfPdr;

	/** 
	 * This attribute maps to the column DES_PRF in the vsa1003_uteprofili table.
	 */
	protected String desPrf;

	/**
	 * Method 'Vsa1003Uteprofili'
	 * 
	 */
	public Vsa1003Uteprofili()
	{
	}

	/**
	 * Method 'getPrgApp'
	 * 
	 * @return int
	 */
	public int getPrgApp()
	{
		return prgApp;
	}

	/**
	 * Method 'setPrgApp'
	 * 
	 * @param prgApp
	 */
	public void setPrgApp(int prgApp)
	{
		this.prgApp = prgApp;
	}

	/**
	 * Method 'getPrgUte'
	 * 
	 * @return int
	 */
	public int getPrgUte()
	{
		return prgUte;
	}

	/**
	 * Method 'setPrgUte'
	 * 
	 * @param prgUte
	 */
	public void setPrgUte(int prgUte)
	{
		this.prgUte = prgUte;
	}

	/**
	 * Method 'getPrgPrfPdr'
	 * 
	 * @return int
	 */
	public int getPrgPrfPdr()
	{
		return prgPrfPdr;
	}

	/**
	 * Method 'setPrgPrfPdr'
	 * 
	 * @param prgPrfPdr
	 */
	public void setPrgPrfPdr(int prgPrfPdr)
	{
		this.prgPrfPdr = prgPrfPdr;
	}

	/**
	 * Method 'getPrgPrfFgl'
	 * 
	 * @return int
	 */
	public int getPrgPrfFgl()
	{
		return prgPrfFgl;
	}

	/**
	 * Method 'setPrgPrfFgl'
	 * 
	 * @param prgPrfFgl
	 */
	public void setPrgPrfFgl(int prgPrfFgl)
	{
		this.prgPrfFgl = prgPrfFgl;
	}

	/**
	 * Method 'getDesPrfPdr'
	 * 
	 * @return String
	 */
	public String getDesPrfPdr()
	{
		return desPrfPdr;
	}

	/**
	 * Method 'setDesPrfPdr'
	 * 
	 * @param desPrfPdr
	 */
	public void setDesPrfPdr(String desPrfPdr)
	{
		this.desPrfPdr = desPrfPdr;
	}

	/**
	 * Method 'getDesPrf'
	 * 
	 * @return String
	 */
	public String getDesPrf()
	{
		return desPrf;
	}

	/**
	 * Method 'setDesPrf'
	 * 
	 * @param desPrf
	 */
	public void setDesPrf(String desPrf)
	{
		this.desPrf = desPrf;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Vsa1003Uteprofili)) {
			return false;
		}
		
		final Vsa1003Uteprofili _cast = (Vsa1003Uteprofili) _other;
		if (prgApp != _cast.prgApp) {
			return false;
		}
		
		if (prgUte != _cast.prgUte) {
			return false;
		}
		
		if (prgPrfPdr != _cast.prgPrfPdr) {
			return false;
		}
		
		if (prgPrfFgl != _cast.prgPrfFgl) {
			return false;
		}
		
		if (desPrfPdr == null ? _cast.desPrfPdr != desPrfPdr : !desPrfPdr.equals( _cast.desPrfPdr )) {
			return false;
		}
		
		if (desPrf == null ? _cast.desPrf != desPrf : !desPrf.equals( _cast.desPrf )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + prgApp;
		_hashCode = 29 * _hashCode + prgUte;
		_hashCode = 29 * _hashCode + prgPrfPdr;
		_hashCode = 29 * _hashCode + prgPrfFgl;
		if (desPrfPdr != null) {
			_hashCode = 29 * _hashCode + desPrfPdr.hashCode();
		}
		
		if (desPrf != null) {
			_hashCode = 29 * _hashCode + desPrf.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "comws.flau.ci.dto.Vsa1003Uteprofili: " );
		ret.append( "prgApp=" + prgApp );
		ret.append( ", prgUte=" + prgUte );
		ret.append( ", prgPrfPdr=" + prgPrfPdr );
		ret.append( ", prgPrfFgl=" + prgPrfFgl );
		ret.append( ", desPrfPdr=" + desPrfPdr );
		ret.append( ", desPrf=" + desPrf );
		return ret.toString();
	}

}
