/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package comws.flau.ci.dto;

import comws.flau.ci.dao.*;
import comws.flau.ci.factory.*;
import comws.flau.ci.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class Vsa1002Utefunz implements Serializable
{
	/** 
	 * This attribute maps to the column PRG_UTE in the vsa1002_utefunz table.
	 */
	protected int prgUte;

	/** 
	 * This attribute maps to the column DES_UTE in the vsa1002_utefunz table.
	 */
	protected String desUte;

	/** 
	 * This attribute maps to the column COD_FISCALE in the vsa1002_utefunz table.
	 */
	protected String codFiscale;

	/** 
	 * This attribute maps to the column DES_IND_EMAIL in the vsa1002_utefunz table.
	 */
	protected String desIndEmail;

	/** 
	 * This attribute maps to the column DES_PSW in the vsa1002_utefunz table.
	 */
	protected String desPsw;

	/** 
	 * This attribute maps to the column DES_COG in the vsa1002_utefunz table.
	 */
	protected String desCog;

	/** 
	 * This attribute maps to the column DES_NOM in the vsa1002_utefunz table.
	 */
	protected String desNom;

	/** 
	 * This attribute maps to the column PRG_APP in the vsa1002_utefunz table.
	 */
	protected int prgApp;

	/** 
	 * This attribute represents whether the primitive attribute prgApp is null.
	 */
	protected boolean prgAppNull = true;

	/** 
	 * This attribute maps to the column DES_PRF_PDR in the vsa1002_utefunz table.
	 */
	protected String desPrfPdr;

	/** 
	 * This attribute maps to the column DES_PRF in the vsa1002_utefunz table.
	 */
	protected String desPrf;

	/** 
	 * This attribute maps to the column PRG_PRF_PDR in the vsa1002_utefunz table.
	 */
	protected int prgPrfPdr;

	/** 
	 * This attribute represents whether the primitive attribute prgPrfPdr is null.
	 */
	protected boolean prgPrfPdrNull = true;

	/** 
	 * This attribute maps to the column PRG_PRF_FGL in the vsa1002_utefunz table.
	 */
	protected int prgPrfFgl;

	/** 
	 * This attribute represents whether the primitive attribute prgPrfFgl is null.
	 */
	protected boolean prgPrfFglNull = true;

	/** 
	 * This attribute maps to the column ORD_FNZ in the vsa1002_utefunz table.
	 */
	protected int ordFnz;

	/** 
	 * This attribute represents whether the primitive attribute ordFnz is null.
	 */
	protected boolean ordFnzNull = true;

	/** 
	 * This attribute maps to the column DES_FNZ in the vsa1002_utefunz table.
	 */
	protected String desFnz;

	/** 
	 * This attribute maps to the column DES_URL in the vsa1002_utefunz table.
	 */
	protected String desUrl;

	/** 
	 * This attribute maps to the column FLG_H24 in the vsa1002_utefunz table.
	 */
	protected String flgH24;

	/**
	 * Method 'Vsa1002Utefunz'
	 * 
	 */
	public Vsa1002Utefunz()
	{
	}

	/**
	 * Method 'getPrgUte'
	 * 
	 * @return int
	 */
	public int getPrgUte()
	{
		return prgUte;
	}

	/**
	 * Method 'setPrgUte'
	 * 
	 * @param prgUte
	 */
	public void setPrgUte(int prgUte)
	{
		this.prgUte = prgUte;
	}

	/**
	 * Method 'getDesUte'
	 * 
	 * @return String
	 */
	public String getDesUte()
	{
		return desUte;
	}

	/**
	 * Method 'setDesUte'
	 * 
	 * @param desUte
	 */
	public void setDesUte(String desUte)
	{
		this.desUte = desUte;
	}

	/**
	 * Method 'getCodFiscale'
	 * 
	 * @return String
	 */
	public String getCodFiscale()
	{
		return codFiscale;
	}

	/**
	 * Method 'setCodFiscale'
	 * 
	 * @param codFiscale
	 */
	public void setCodFiscale(String codFiscale)
	{
		this.codFiscale = codFiscale;
	}

	/**
	 * Method 'getDesIndEmail'
	 * 
	 * @return String
	 */
	public String getDesIndEmail()
	{
		return desIndEmail;
	}

	/**
	 * Method 'setDesIndEmail'
	 * 
	 * @param desIndEmail
	 */
	public void setDesIndEmail(String desIndEmail)
	{
		this.desIndEmail = desIndEmail;
	}

	/**
	 * Method 'getDesPsw'
	 * 
	 * @return String
	 */
	public String getDesPsw()
	{
		return desPsw;
	}

	/**
	 * Method 'setDesPsw'
	 * 
	 * @param desPsw
	 */
	public void setDesPsw(String desPsw)
	{
		this.desPsw = desPsw;
	}

	/**
	 * Method 'getDesCog'
	 * 
	 * @return String
	 */
	public String getDesCog()
	{
		return desCog;
	}

	/**
	 * Method 'setDesCog'
	 * 
	 * @param desCog
	 */
	public void setDesCog(String desCog)
	{
		this.desCog = desCog;
	}

	/**
	 * Method 'getDesNom'
	 * 
	 * @return String
	 */
	public String getDesNom()
	{
		return desNom;
	}

	/**
	 * Method 'setDesNom'
	 * 
	 * @param desNom
	 */
	public void setDesNom(String desNom)
	{
		this.desNom = desNom;
	}

	/**
	 * Method 'getPrgApp'
	 * 
	 * @return int
	 */
	public int getPrgApp()
	{
		return prgApp;
	}

	/**
	 * Method 'setPrgApp'
	 * 
	 * @param prgApp
	 */
	public void setPrgApp(int prgApp)
	{
		this.prgApp = prgApp;
		this.prgAppNull = false;
	}

	/**
	 * Method 'setPrgAppNull'
	 * 
	 * @param value
	 */
	public void setPrgAppNull(boolean value)
	{
		this.prgAppNull = value;
	}

	/**
	 * Method 'isPrgAppNull'
	 * 
	 * @return boolean
	 */
	public boolean isPrgAppNull()
	{
		return prgAppNull;
	}

	/**
	 * Method 'getDesPrfPdr'
	 * 
	 * @return String
	 */
	public String getDesPrfPdr()
	{
		return desPrfPdr;
	}

	/**
	 * Method 'setDesPrfPdr'
	 * 
	 * @param desPrfPdr
	 */
	public void setDesPrfPdr(String desPrfPdr)
	{
		this.desPrfPdr = desPrfPdr;
	}

	/**
	 * Method 'getDesPrf'
	 * 
	 * @return String
	 */
	public String getDesPrf()
	{
		return desPrf;
	}

	/**
	 * Method 'setDesPrf'
	 * 
	 * @param desPrf
	 */
	public void setDesPrf(String desPrf)
	{
		this.desPrf = desPrf;
	}

	/**
	 * Method 'getPrgPrfPdr'
	 * 
	 * @return int
	 */
	public int getPrgPrfPdr()
	{
		return prgPrfPdr;
	}

	/**
	 * Method 'setPrgPrfPdr'
	 * 
	 * @param prgPrfPdr
	 */
	public void setPrgPrfPdr(int prgPrfPdr)
	{
		this.prgPrfPdr = prgPrfPdr;
		this.prgPrfPdrNull = false;
	}

	/**
	 * Method 'setPrgPrfPdrNull'
	 * 
	 * @param value
	 */
	public void setPrgPrfPdrNull(boolean value)
	{
		this.prgPrfPdrNull = value;
	}

	/**
	 * Method 'isPrgPrfPdrNull'
	 * 
	 * @return boolean
	 */
	public boolean isPrgPrfPdrNull()
	{
		return prgPrfPdrNull;
	}

	/**
	 * Method 'getPrgPrfFgl'
	 * 
	 * @return int
	 */
	public int getPrgPrfFgl()
	{
		return prgPrfFgl;
	}

	/**
	 * Method 'setPrgPrfFgl'
	 * 
	 * @param prgPrfFgl
	 */
	public void setPrgPrfFgl(int prgPrfFgl)
	{
		this.prgPrfFgl = prgPrfFgl;
		this.prgPrfFglNull = false;
	}

	/**
	 * Method 'setPrgPrfFglNull'
	 * 
	 * @param value
	 */
	public void setPrgPrfFglNull(boolean value)
	{
		this.prgPrfFglNull = value;
	}

	/**
	 * Method 'isPrgPrfFglNull'
	 * 
	 * @return boolean
	 */
	public boolean isPrgPrfFglNull()
	{
		return prgPrfFglNull;
	}

	/**
	 * Method 'getOrdFnz'
	 * 
	 * @return int
	 */
	public int getOrdFnz()
	{
		return ordFnz;
	}

	/**
	 * Method 'setOrdFnz'
	 * 
	 * @param ordFnz
	 */
	public void setOrdFnz(int ordFnz)
	{
		this.ordFnz = ordFnz;
		this.ordFnzNull = false;
	}

	/**
	 * Method 'setOrdFnzNull'
	 * 
	 * @param value
	 */
	public void setOrdFnzNull(boolean value)
	{
		this.ordFnzNull = value;
	}

	/**
	 * Method 'isOrdFnzNull'
	 * 
	 * @return boolean
	 */
	public boolean isOrdFnzNull()
	{
		return ordFnzNull;
	}

	/**
	 * Method 'getDesFnz'
	 * 
	 * @return String
	 */
	public String getDesFnz()
	{
		return desFnz;
	}

	/**
	 * Method 'setDesFnz'
	 * 
	 * @param desFnz
	 */
	public void setDesFnz(String desFnz)
	{
		this.desFnz = desFnz;
	}

	/**
	 * Method 'getDesUrl'
	 * 
	 * @return String
	 */
	public String getDesUrl()
	{
		return desUrl;
	}

	/**
	 * Method 'setDesUrl'
	 * 
	 * @param desUrl
	 */
	public void setDesUrl(String desUrl)
	{
		this.desUrl = desUrl;
	}

	/**
	 * Method 'getFlgH24'
	 * 
	 * @return String
	 */
	public String getFlgH24()
	{
		return flgH24;
	}

	/**
	 * Method 'setFlgH24'
	 * 
	 * @param flgH24
	 */
	public void setFlgH24(String flgH24)
	{
		this.flgH24 = flgH24;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Vsa1002Utefunz)) {
			return false;
		}
		
		final Vsa1002Utefunz _cast = (Vsa1002Utefunz) _other;
		if (prgUte != _cast.prgUte) {
			return false;
		}
		
		if (desUte == null ? _cast.desUte != desUte : !desUte.equals( _cast.desUte )) {
			return false;
		}
		
		if (codFiscale == null ? _cast.codFiscale != codFiscale : !codFiscale.equals( _cast.codFiscale )) {
			return false;
		}
		
		if (desIndEmail == null ? _cast.desIndEmail != desIndEmail : !desIndEmail.equals( _cast.desIndEmail )) {
			return false;
		}
		
		if (desPsw == null ? _cast.desPsw != desPsw : !desPsw.equals( _cast.desPsw )) {
			return false;
		}
		
		if (desCog == null ? _cast.desCog != desCog : !desCog.equals( _cast.desCog )) {
			return false;
		}
		
		if (desNom == null ? _cast.desNom != desNom : !desNom.equals( _cast.desNom )) {
			return false;
		}
		
		if (prgApp != _cast.prgApp) {
			return false;
		}
		
		if (prgAppNull != _cast.prgAppNull) {
			return false;
		}
		
		if (desPrfPdr == null ? _cast.desPrfPdr != desPrfPdr : !desPrfPdr.equals( _cast.desPrfPdr )) {
			return false;
		}
		
		if (desPrf == null ? _cast.desPrf != desPrf : !desPrf.equals( _cast.desPrf )) {
			return false;
		}
		
		if (prgPrfPdr != _cast.prgPrfPdr) {
			return false;
		}
		
		if (prgPrfPdrNull != _cast.prgPrfPdrNull) {
			return false;
		}
		
		if (prgPrfFgl != _cast.prgPrfFgl) {
			return false;
		}
		
		if (prgPrfFglNull != _cast.prgPrfFglNull) {
			return false;
		}
		
		if (ordFnz != _cast.ordFnz) {
			return false;
		}
		
		if (ordFnzNull != _cast.ordFnzNull) {
			return false;
		}
		
		if (desFnz == null ? _cast.desFnz != desFnz : !desFnz.equals( _cast.desFnz )) {
			return false;
		}
		
		if (desUrl == null ? _cast.desUrl != desUrl : !desUrl.equals( _cast.desUrl )) {
			return false;
		}
		
		if (flgH24 == null ? _cast.flgH24 != flgH24 : !flgH24.equals( _cast.flgH24 )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + prgUte;
		if (desUte != null) {
			_hashCode = 29 * _hashCode + desUte.hashCode();
		}
		
		if (codFiscale != null) {
			_hashCode = 29 * _hashCode + codFiscale.hashCode();
		}
		
		if (desIndEmail != null) {
			_hashCode = 29 * _hashCode + desIndEmail.hashCode();
		}
		
		if (desPsw != null) {
			_hashCode = 29 * _hashCode + desPsw.hashCode();
		}
		
		if (desCog != null) {
			_hashCode = 29 * _hashCode + desCog.hashCode();
		}
		
		if (desNom != null) {
			_hashCode = 29 * _hashCode + desNom.hashCode();
		}
		
		_hashCode = 29 * _hashCode + prgApp;
		_hashCode = 29 * _hashCode + (prgAppNull ? 1 : 0);
		if (desPrfPdr != null) {
			_hashCode = 29 * _hashCode + desPrfPdr.hashCode();
		}
		
		if (desPrf != null) {
			_hashCode = 29 * _hashCode + desPrf.hashCode();
		}
		
		_hashCode = 29 * _hashCode + prgPrfPdr;
		_hashCode = 29 * _hashCode + (prgPrfPdrNull ? 1 : 0);
		_hashCode = 29 * _hashCode + prgPrfFgl;
		_hashCode = 29 * _hashCode + (prgPrfFglNull ? 1 : 0);
		_hashCode = 29 * _hashCode + ordFnz;
		_hashCode = 29 * _hashCode + (ordFnzNull ? 1 : 0);
		if (desFnz != null) {
			_hashCode = 29 * _hashCode + desFnz.hashCode();
		}
		
		if (desUrl != null) {
			_hashCode = 29 * _hashCode + desUrl.hashCode();
		}
		
		if (flgH24 != null) {
			_hashCode = 29 * _hashCode + flgH24.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "comws.flau.ci.dto.Vsa1002Utefunz: " );
		ret.append( "prgUte=" + prgUte );
		ret.append( ", desUte=" + desUte );
		ret.append( ", codFiscale=" + codFiscale );
		ret.append( ", desIndEmail=" + desIndEmail );
		ret.append( ", desPsw=" + desPsw );
		ret.append( ", desCog=" + desCog );
		ret.append( ", desNom=" + desNom );
		ret.append( ", prgApp=" + prgApp );
		ret.append( ", desPrfPdr=" + desPrfPdr );
		ret.append( ", desPrf=" + desPrf );
		ret.append( ", prgPrfPdr=" + prgPrfPdr );
		ret.append( ", prgPrfFgl=" + prgPrfFgl );
		ret.append( ", ordFnz=" + ordFnz );
		ret.append( ", desFnz=" + desFnz );
		ret.append( ", desUrl=" + desUrl );
		ret.append( ", flgH24=" + flgH24 );
		return ret.toString();
	}

}
